### PR TITLE
Make @SpringMock work for beans with @Primary

### LINKED ISSUE #1502: Unable to mock a Spring primary bean when other instances are available
### Describe the bug

In larger Spring Boot's codebases it's not uncommon to have multiple beans of the same type where one of them is marked as `@Primary`.

Attempting to mock such bean with `@SpringBean` doesn't work as Spock Spring requires exactly one mocked bean's instance in the context (regardless of whether one of them is marked as primary).

This is an unnecessary limitation, especially that spring-boot-starter-test doesn't pose such limit when using `@MockBean`.

You can find a sample project presenting this issue with tests written using both `SpringBean` and `MockBean` here:
https://github.com/konradczajka/spock-spring-issue

The problem seems to be located in `SpockMockPostprocessor` which doesn't checks if one of located beans is marked as primary. I'd gladly provide a PR with a solution which seems to be working locally (which is highly inspired by the spring-boot-starter-test's code) 

### To Reproduce

With context configured as follows:
```
@Bean
Service2 service2NotPrimary() {
    new Service2()
}

@Primary
@Bean
Service2 service2Primary() {
    new Service2()
}

@Bean
IService1 service1(Service2 service2) {
    return new Service1(service2)
}
```
and a test like this:
```
@SpringBean
Service2 service2 = Mock() {
    generateQuickBrownFox() >> "blubb"
}

@Autowired
Service1 service1

def "injection with stubbing works"() {
    expect:
    service1.generateString() == "blubb"
}
```

### Expected behavior

Passing test

### Actual behavior

The test fails with a message similar to this:
```
Unable to register mock beanService2 expected a single matching bean to replace but found [service2Primary, service2NotPrimary]
```

### Java version

18, but different versions don't affect the outcome

### Buildtool version

18, but different versions don't affect the outcome

### What operating system are you using

Linux

### Dependencies

```
plugins {
	id 'org.springframework.boot' version '2.7.2'
	id 'io.spring.dependency-management' version '1.0.12.RELEASE'
	id 'java'
	id 'groovy'
}

dependencies {
	implementation 'org.springframework.boot:spring-boot-starter'
	testImplementation 'org.springframework.boot:spring-boot-starter-test'
	testImplementation 'org.spockframework:spock-core:2.1-groovy-3.0'
	testImplementation 'org.spockframework:spock-spring:2.1-groovy-3.0'
}
```

### Additional context

The same test written in Java/Mockito with `spring-boot-starter-test` and its `@MockBean` works as intended.

### PR DESCRIPTION
**Pull request by konradczajka**
fixes #1502

When the context contains multiple beans for given interface
but one of them is marked as @Primary it should be possible
to mock this interface.

Current implementation doesn't check if one of found beans is primary
and fails with an exception.

My change mirrors a similar logic used in spring-boot-starter-test
and resolves this issue.

### CODE REVIEW

File: spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java [hunk 1]
```diff
@@ -153,12 +155,37 @@ private String getBeanName(ConfigurableListableBeanFactory beanFactory,
...
+  private String determinePrimaryCandidate(BeanDefinitionRegistry registry, Collection<String> candidateBeanNames,
+                                           ResolvableType type) {
+    String primaryBeanName = null;
+    for (String candidateBeanName : candidateBeanNames) {
+      BeanDefinition beanDefinition = registry.getBeanDefinition(candidateBeanName);
+      if (beanDefinition.isPrimary()) {
+        if (primaryBeanName != null) {
+          throw new NoUniqueBeanDefinitionException(type.resolve(), candidateBeanNames.size(),
+            "more than one 'primary' bean found among candidates: "
+              + Collections.singletonList(candidateBeanNames));
```
Comment (leonard84) [inline spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java:177]: Why do you wrap the collection in another list?
And this should also be tested.

**Review by leonard84 — CHANGES_REQUESTED** [review]

**Comment by leonard84** [comment]
Could you also check if there are other relevant new additions that were made to `MockitoPostProcessor` that are missing in `SpockMockPostProcessor`?

File: spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java (hunk 1 above)
Comment (konradczajka) [reply spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java:177]: You're right - I'll cover this scenario.

As for the first question I'll rephrase it a bit - why do I add this method when it's already present in this class :)

Although in a very slightly different form:
```
  private String determinePrimaryCandidate(BeanDefinitionRegistry registry,
                                           String[] candidateBeanNames, ResolvableType type) {
    String primaryBeanName = null;
    for (String candidateBeanName : candidateBeanNames) {
      BeanDefinition beanDefinition = registry.getBeanDefinition(candidateBeanName);
      if (beanDefinition.isPrimary()) {
        if (primaryBeanName != null) {
          throw new NoUniqueBeanDefinitionException(type.resolve(),
            candidateBeanNames.length,
            "more than one 'primary' bean found among candidates: "
              + asList(candidateBeanNames));
        }
        primaryBeanName = candidateBeanName;
      }
    }
    return primaryBeanName;
  }
```

I'll reuse the existing method and add a test(s) to make the coverage better. Thank you for reporting this.

Comment (konradczajka) [reply spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java]: @leonard84 I'll need an assistance with writing tests assertions for "failure" cases. I get different error responses depnding on whether I run tests using `:test` or `:testCglib`.

**Comment by konradczajka** [comment]
> Could you also check if there are other relevant new additions that were made to MockitoPostProcessor that are missing in SpockMockPostProcessor?

Yes, I'll check it tomorrow.

**Comment by konradczajka** [comment]
> Could you also check if there are other relevant new additions that were made to MockitoPostProcessor that are missing in SpockMockPostProcessor?

I found four bugfixes applied to the `MockitoPostProcessor` that seems to be missing in the `SpockMockPostProcessor`. One of them had been reverted later as it caused other problems. That leaves those three:
[29639](https://github.com/spring-projects/spring-boot/issues/29639), [27693](https://github.com/spring-projects/spring-boot/issues/27693), [20665](https://github.com/spring-projects/spring-boot/issues/20665). Apart from them there were ~4 PRs with refactorings/code polishing. 

I'll try to write a test for each of mentioned issues and port the fix if the test won't pass.

File: spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java (hunk 1 above)
Comment (leonard84) [reply spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java]: Have a look at https://github.com/spockframework/spock/blob/master/spock-spring/src/test/groovy/org/spockframework/spring/mock/imported/SpringSpyWithAopProxyTests.groovy#L50-L55 there where other instances where ByteBuddy and Cglib behaved differently, maybe this helps. Could also check if those test cases need updating, they where all ported from spring boot.

Comment (konradczajka) [reply spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java]: In my case Spring context is not loaded (which is expected) but when I use cglib, the actual failure of the nested test is `MultipleFailuresError` aggregating: context loading exception and `ClassPathException` ("org.spockframework.mock.CannotCreateMockException: Cannot create mock for class org.spockframework.spring.Service2").

The suggested `@PendingFeatureIf` usage would just make the test ignored which is not what I want.
My second idea was to check the system prop "ignoreByteBuddy" in the "then:" section and make assertions for expected failures for both cases but it turned out that cglib throws mentioned `ClassPathException` only when the feature is run within a bigger suite. When the the test was run alone, it behave the same way as with bytebuddy.

I though about writing a custom assertion method (just for this scenario) which would check if the failure was either the expected context initialization exception or `MultipleFailuresError` wrapping it but it turned out to be quite ugly.

I decided to just go with relaxed verification and just check if the error message contains "Failed to load ApplicationContext".

As for the test you've linked - it still doesn't pass for bytebuddy, where AoP (caching in that cased) gets messed up. It seems to have a different cause. I could try to port [the commit](https://github.com/spring-projects/spring-boot/commit/cdfbf28099b30621a118ebf2ec4988364295b610#diff-453b385bff6088b749d762f45d50b90aeed5799fb8d771ea614132997d0ca2a1), which closed [the related issue](https://github.com/spring-projects/spring-boot/issues/5837) but it extends the public API (new param for `SpringBean` annotation) and therefore deserves a separate PR.

File: spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java [hunk 2]
```diff
@@ -199,8 +182,8 @@ private void registerSpy(ConfigurableListableBeanFactory beanFactory,
     }
   }
 
-  private Set<String> findCandidateBeans(ConfigurableListableBeanFactory beanFactory,
-                                         MockDefinition mockDefinition) {
+  private String[] findCandidateBeans(ConfigurableListableBeanFactory beanFactory,
```
Comment (leonard84) [inline spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java:186]: Why the switch to an array? The spring code also still uses a `Set`?

File: spock-spring/src/test/groovy/org/spockframework/spring/mock/SpringBeanWithManyOrNoPrimarySpec.groovy [hunk 3]
```diff
@@ -0,0 +1,122 @@
...
+
+  def foo() {
+    expect:
+    1==1
+  }
+
+  static class TwoService2BeansWithMultiplePrimaryConfig {
+
+    @Bean
+    Service2 service2Primary1() {
```
Comment (leonard84) [inline spock-spring/src/test/groovy/org/spockframework/spring/mock/SpringBeanWithManyOrNoPrimarySpec.groovy:51]: The name is misleading as this is actually not a primary bean

**Review by leonard84 — CHANGES_REQUESTED** [review]

File: spock-spring/src/test/groovy/org/spockframework/spring/mock/SpringBeanWithManyOrNoPrimarySpec.groovy (hunk 3 above)
Comment (konradczajka) [reply spock-spring/src/test/groovy/org/spockframework/spring/mock/SpringBeanWithManyOrNoPrimarySpec.groovy:51]: Of course, will fix it, thanks

File: spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java (hunk 2 above)
Comment (konradczajka) [reply spock-spring/src/main/java/org/spockframework/spring/mock/SpockMockPostprocessor.java:186]: I've changed it to make it more consistent with such methods as `determinePrimaryCandidate` but it will be better to do it other way around and migrate both to Set/Collection (following the original code).

**Comment by konradczajka** [comment]
Hi @leonard84 
Is there anything else you'd like to be changed in this PR or can it be merged?

**Review by leonard84 — APPROVED** [review]
Thanks for the fix @konradczajka
