### PR TITLE
Use Lookup class loading strategy if available

### LINKED ISSUE #843: Requirement for Java 11 compatibility
Java 11 is going to be the first LTS version of Java and it will remove support for `sun.misc.Unsafe::defineClass` which is currently used by both Byte Buddy and cglib.

As of Java 11, this loading approach does no longer work but since Byte Buddy 1.8 there is a new way of loading classes that unfortunately requires some code changes in Spock as method handle lookups are call site sensitive: https://mydailyjava.blogspot.no/2018/04/jdk-11-and-proxies-in-world-past.html 

You need to invoke the `load` method in `ProxyBasedMockFactory` to use a class loading strategy that depends on the current JVM's capabilities. The code looks like the following: 

```java
ClassLoadingStrategy<ClassLoader> strategy;
if (ClassInjector.UsingLookup.isAvailable()) {
  Class<?> methodHandles = Class.forName("java.lang.invoke.MethodHandles");
  Object lookup = methodHandles.getMethod("lookup").invoke(null);
  Method privateLookupIn = methodHandles.getMethod("privateLookupIn", 
      Class.class, 
      Class.forName("java.lang.invoke.MethodHandles$Lookup"));
  Object privateLookup = privateLookupIn.invoke(null, targetClass, lookup);
  strategy = ClassLoadingStrategy.UsingLookup.of(privateLookup);
} else if (ClassInjector.UsingReflection.isAvailable()) {
  strategy = ClassLoadingStrateg.Default.INJECTION;
} else {
  throw new IllegalStateException(“No code loading strategy available”);
}
```

The `Method` and the base `lookup` instance should be reused to avoid an overhead if the `lookup` strategy is available.

Also, using this strategy, you probably need to change the naming strategy for `java.*` types as you cannot define classes in a random package. Instead, put those types into a dedicated package that contains another class that you own and resolve the private lookup against this class. The class can for example be `org.spockframework.loading.Hook` and then name classes that start with `java.*` by `org.spockframework.loading`.

I am currently on parental leave without too much time. I will send you a PR if I get a quite moment but its not a big change, so maybe you can find the time to do it yourself.

### PR DESCRIPTION
**Pull request by marcphilipp**
In order to create mock objects on Java 11, `ProxyBasedMockFactory` now uses ByteBuddy's `Lookup`-based `ClassLoadingStrategy`, if available.

Resolves #843.

### CODE REVIEW

File: spock-core/src/main/java/org/spockframework/mock/codegen/CodegenDummy.java [hunk 1]
```diff
@@ -0,0 +1,11 @@
+package org.spockframework.mock.codegen;
+
+/**
+ * Serves as a reference point for method handle based class loading and is makes the containing package
+ * non-empty so generated classes can be legally defined inside of it.
+ */
+public class CodegenDummy {
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/mock/codegen/CodegenDummy.java]: I'd call it `CodegenTarget`

File: spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java [hunk 2]
```diff
@@ -102,11 +109,19 @@ static Object createMock(final Class<?> type,
         new Callable<Class<?>>() {
           @Override
           public Class<?> call() throws Exception {
+            String typeName = type.getName();
+            Class<?> targetClass = type;
+            if (shouldLoadIntoCodegenPackage(type)) {
+              typeName = CODEGEN_PACKAGE + "." + type.getSimpleName();
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java]: should't the type name be the prefix + FQCN, otherwise we might have conflicts

File: spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java [hunk 3]
```diff
@@ -89,6 +93,9 @@ private Object createDynamicProxyMock(Class<?> mockType, List<Class<?>> addition
 
     private static final TypeCache<TypeCache.SimpleKey> CACHE =
       new TypeCache.WithInlineExpunction<>(TypeCache.Sort.SOFT);
+    private static final Random RANDOM = new Random();
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java]: hm Random is not thread-safe IIRC that about ThreadLocalRandom?

File: spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java [hunk 4]
```diff
@@ -127,6 +142,42 @@ static Object createMock(final Class<?> type,
...
+        Method lookupMethod = methodHandlesClass.getMethod("lookup");
+        Method privateLookupInMethod = methodHandlesClass.getMethod("privateLookupIn", Class.class, lookupClass);
+        Object lookup = lookupMethod.invoke(null);
+        Object privateLookup = privateLookupInMethod.invoke(null, targetClass, lookup);
+        return ClassLoadingStrategy.UsingLookup.of(privateLookup);
+      }
+      if (ClassInjector.UsingReflection.isAvailable()) {
+        return ClassLoadingStrategy.Default.INJECTION;
+      }
+      throw new IllegalStateException("No class loading strategy available");
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java]: Shouldn't we fall back to `WRAPPER`

File: spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java (hunk 3 above)
Comment (marcphilipp) [reply spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java]: > Instances of java.util.Random are threadsafe. However, the concurrent use of the same java.util.Random instance across threads may encounter contention and consequent poor performance. Consider instead using java.util.concurrent.ThreadLocalRandom in multithreaded designs.

So it's thread-safe but may have poor performance... I'll change it to `ThreadLocalRandom`.

File: spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java (hunk 4 above)
Comment (marcphilipp) [reply spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java]: In which cases would that get used?

File: spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java (hunk 2 above)
Comment (marcphilipp) [reply spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java]: AFAIK the type needs to have the same package as the `targetClass`.

This is how Mockito does it:

https://github.com/mockito/mockito/blob/4f72147c464c1a8a642d01fc3334e98e92b464cd/src/main/java/org/mockito/internal/creation/bytebuddy/SubclassBytecodeGenerator.java#L138-L146

https://github.com/mockito/mockito/blob/4f72147c464c1a8a642d01fc3334e98e92b464cd/src/main/java/org/mockito/internal/creation/bytebuddy/SubclassInjectionLoader.java#L42

File: spock-core/src/main/java/org/spockframework/mock/codegen/CodegenDummy.java (hunk 1 above)
Comment (marcphilipp) [reply spock-core/src/main/java/org/spockframework/mock/codegen/CodegenDummy.java]: Fine with me. 👍

File: spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java (hunk 2 above)
Comment (leonard84) [reply spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java]: Hm, ok confilcts are avoided via the random Int at the end.

File: spock-core/src/main/java/org/spockframework/mock/codegen/CodegenDummy.java (hunk 1 above)
Comment (marcphilipp) [reply spock-core/src/main/java/org/spockframework/mock/codegen/CodegenDummy.java]: How about just `Target`?

**Comment by leonard84** [comment]
The code should include a notice of origin pointing to Mockito

What about the classloader check https://github.com/mockito/mockito/blob/4f72147c464c1a8a642d01fc3334e98e92b464cd/src/main/java/org/mockito/internal/creation/bytebuddy/SubclassInjectionLoader.java#L75 don't we need this also?

**Comment by leonard84** [comment]
@raphw maybe you could also take a look

File: spock-core/src/main/java/org/spockframework/mock/codegen/CodegenDummy.java (hunk 1 above)
Comment (leonard84) [reply spock-core/src/main/java/org/spockframework/mock/codegen/CodegenDummy.java]: also ok

File: spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java (hunk 2 above)
Comment (raphw) [reply spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java]: The exact package is important here as this is how method handle lookups work. There are no package hierarchies with sub packages, they are just distinct. This is correct.

File: spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java (hunk 4 above)
Comment (raphw) [reply spock-core/src/main/java/org/spockframework/mock/runtime/ProxyBasedMockFactory.java]: If a pre Java-9 JVM does not support Unsafe but I would not know any.

**Comment by raphw** [comment]
Mockito sometimes creates class loaders if a mock is loaded by a class loader that cannot see Mockito. This is a problem especially in OSGi environments, therefore the indirection and the check.

**Comment by raphw** [comment]
Looks good otherwise!

**Comment by marcphilipp** [comment]
@leonard84 PTAL! 🙂
