### PR TITLE
Make RetryExtension more parallel-safe (#1700)

### LINKED ISSUE #1700: `@Retry` with mode `SETUP_FEATURE_CLEANUP` is not fully parallel-safe (swallowing failures or throwing `NullPointerException`)
### Describe the bug

The `RetryExtension` with mode `SETUP_FEATURE_CLEANUP` uses an outer and an inner interceptor.
The outer is used as iteration interceptor the inner as feature method interceptor.
The outer in its before-action sets a `ThreadLocal` to a collection where exceptions are collected.
The inner adds exceptions that happened to this collection.

The problem is, if you have a work-around for junit-team/junit5#3108 in place, or it will be done like that in JUnit Platform later on, the problem is, that the feature method can be run on a different thread than the iteration interceptor.

This causes one of two problems.

Either the thread-local collection for the thread the iteration is running on was initialized by some interceptor for another test, then failures happening are just swallowed and never reported and the test looks like it is successful while it actually was failing.

Or the thread-local collection for the thread the iteration is running on was not yet initialized and you get this `NullPointerException`:
```stacktrace
java.lang.NullPointerException
	at org.spockframework.runtime.extension.builtin.RetryIterationInterceptor$IterationState.failIteration(RetryIterationInterceptor.java:89)
	at org.spockframework.runtime.extension.builtin.RetryIterationInterceptor$InnerRetryInterceptor.intercept(RetryIterationInterceptor.java:68)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:101)
	at net.kautler.command.integ.test.spock.CDIExtension.visitSpec_closure1$_closure2(CDIExtension.groovy:44)
	at groovy.lang.Closure.call(Closure.java:412)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:101)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.spockframework.runtime.model.MethodInfo.invoke(MethodInfo.java:156)
	at org.spockframework.runtime.extension.MethodInvocation.proceed(MethodInvocation.java:102)
	at groovy.lang.Closure.call(Closure.java:412)
	at groovy.lang.Closure.call(Closure.java:406)
	at groovy.lang.Closure.run(Closure.java:493)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

### To Reproduce

Add an iteration interceptor that is run after the retry interceptor with the following implementation:
```groovy
new Thread({ invocation.proceed() }).tap {
    it.start()
    it.join()
}
```
and use `Retry` with mode `SETUP_FEATURE_CLEANUP`.

### Expected behavior

Retrying working as usual

### Actual behavior

`NullPointerException` thrown

### Java version

8

### Buildtool version

Gradle 8.1.1

### What operating system are you using

Windows

### Dependencies

Spock 2.3-groovy-3.0

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #1700

### CODE REVIEW

**Comment by Vampire** [comment]
Current dependencies on/for this PR:
* master
  * **PR #1701** <a href="https://app.graphite.dev/github/pr/spockframework/spock/1701" target="_blank">Graphite</a>  👈

This comment was auto-generated by [Graphite](https://app.graphite.dev/github/pr/spockframework/spock/1701?utm_source=stack-comment).

File: spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java [hunk 1]
```diff
@@ -74,26 +77,32 @@ public void intercept(IMethodInvocation invocation) throws Throwable {
...
+      throwables.add(failure);
+      if (finalIteration.containsKey(iteration) && finalIteration.get(iteration).get()) {
+        throw new MultipleFailuresError("Retries exhausted", throwables);
       }
     }
 
-    boolean notFailed() {
-      return throwables.get().isEmpty();
+    boolean notFailed(IterationInfo iteration) {
+      return !throwables.containsKey(iteration) || throwables.get(iteration).isEmpty();
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java:105]: The following would save one map lookup and also makes it threadsafe, if throwables map would be cleared (which does currently not happen).

```suggestion
      List<Throwable> list = throwables.get(iteration);
      return list == null || list.isEmpty();
```

File: spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java [hunk 2]
```diff
@@ -74,26 +77,32 @@ public void intercept(IMethodInvocation invocation) throws Throwable {
...
-    void startIteration() {
-      throwables.set(new ArrayList<>());
+    private final Map<IterationInfo, AtomicBoolean> finalIteration = new ConcurrentHashMap<>();
+    private final Map<IterationInfo, List<Throwable>> throwables = new ConcurrentHashMap<>();
+
+    void resetFailures(IterationInfo iteration) {
+      this.throwables.computeIfPresent(iteration, (key, throwables) -> {
+        throwables.clear();
+        return throwables;
+      });
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java:87]: I find it hard to understand that the field and the lamda parameter have the same name.
```suggestion
      this.throwables.computeIfPresent(iteration, (key, throwablesList) -> {
        throwablesList.clear();
        return throwablesList;
      });
```

File: spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java [hunk 3]
```diff
@@ -74,26 +77,32 @@ public void intercept(IMethodInvocation invocation) throws Throwable {
   }
 
   private class IterationState {
-    private final ThreadLocal<Boolean> finalIteration = ThreadLocal.withInitial(() -> false);
-    private final ThreadLocal<List<Throwable>> throwables = new ThreadLocal<>();
-
-    void startIteration() {
-      throwables.set(new ArrayList<>());
+    private final Map<IterationInfo, AtomicBoolean> finalIteration = new ConcurrentHashMap<>();
+    private final Map<IterationInfo, List<Throwable>> throwables = new ConcurrentHashMap<>();
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java:81]: I would prefer the type `ConcurrentMap<IterationInfo, CopyOnWriteArrayList<Throwable>>`.
This would cearly state that the field is threadsafe.

File: spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java [hunk 4]
```diff
@@ -74,26 +77,32 @@ public void intercept(IMethodInvocation invocation) throws Throwable {
   }
 
   private class IterationState {
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java:79]:
```suggestion
  @ThreadSafe
  private class IterationState {
```

File: spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java [hunk 5]
```diff
@@ -74,26 +77,32 @@ public void intercept(IMethodInvocation invocation) throws Throwable {
...
     }
 
-    void failIteration(Throwable failure) {
-      throwables.get().add(failure);
-      if (finalIteration.get()) {
-        throw new MultipleFailuresError("Retries exhausted", throwables.get());
+    void failIteration(IterationInfo iteration, Throwable failure) {
+      List<Throwable> throwables = this.throwables.computeIfAbsent(iteration, key -> new CopyOnWriteArrayList<>());
+      throwables.add(failure);
+      if (finalIteration.containsKey(iteration) && finalIteration.get(iteration).get()) {
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java:99]:
```suggestion
      AtomicBoolean finalIterationValue = finalIteration.get(iteration)
      if (finalIterationValue  != null && finalIterationValue.get()) {
```

File: spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java [hunk 6]
```diff
@@ -74,26 +77,32 @@ public void intercept(IMethodInvocation invocation) throws Throwable {
...
+        .computeIfAbsent(iteration, key -> new AtomicBoolean(false))
+        .set(retryAttempt == retry.count());
     }
 
-    void failIteration(Throwable failure) {
-      throwables.get().add(failure);
-      if (finalIteration.get()) {
-        throw new MultipleFailuresError("Retries exhausted", throwables.get());
+    void failIteration(IterationInfo iteration, Throwable failure) {
+      List<Throwable> throwables = this.throwables.computeIfAbsent(iteration, key -> new CopyOnWriteArrayList<>());
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java:97]: Please rename `throwables` to `throwablesList` or rename `this.throwables` to something like `this.throwablesMap`.

**Review by AndreasTu — CHANGES_REQUESTED** [review]

**Review by AndreasTu — DISMISSED** [review]

File: spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java [hunk 7]
```diff
@@ -40,11 +46,10 @@ public RetryIterationInterceptor(Retry retry, MethodInfo featureMethod) {
 
   @Override
   public void intercept(IMethodInvocation invocation) throws Throwable {
-    iterationState.startIteration();
     for (int i = 0; i <= retry.count(); i++) {
-      iterationState.setRetryAttempt(i);
+      iterationState.setRetryAttempt(invocation.getIteration(), i);
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java:50]: Can we rewrite this now that we have a proper store implementation?

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/runtime/extension/builtin/RetryIterationInterceptor.java]: Definitely :-)

**Review by AndreasTu — APPROVED** [review]

**Review by leonard84 — APPROVED** [review]
