### PR TITLE
ByteBuddy: Do not use Lookup for non-local mocks

### LINKED ISSUE #2017: ByteBuddy-MockMaker uses wrong ClassLoader on Java 21, if mocked type and additional interfaces are from different classloaders
### Describe the bug

Given the following conditions:

- ByteBuddy is available
- We are running on Java 21
- and the following classloader hierarchy:

Unbenannt-2024-07-14-2000

When mocking type `iam.Mocked` with `additionalInterfaces: [foo.Bar]` and if the specification is loaded by `MySpecClassLoader`, we will get the following exception:

<details>
<summary>Stacktrace:</summary>

```
java.lang.IllegalArgumentException: Could not create type
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:170)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:399)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:190)
	at net.bytebuddy.TypeCache$WithInlineExpunction.findOrInsert(TypeCache.java:410)
	at org.spockframework.mock.runtime.ByteBuddyMockFactory.createMock(ByteBuddyMockFactory.java:97)
	at org.spockframework.mock.runtime.ByteBuddyMockMaker.makeMock(ByteBuddyMockMaker.java:63)
	at org.spockframework.mock.runtime.MockMakerRegistry.createWithAppropriateMockMaker(MockMakerRegistry.java:194)
	at org.spockframework.mock.runtime.MockMakerRegistry.makeMockInternal(MockMakerRegistry.java:153)
	at org.spockframework.mock.runtime.MockMakerRegistry.makeMock(MockMakerRegistry.java:125)
	at org.spockframework.mock.runtime.JavaMockFactory.createInternal(JavaMockFactory.java:56)
	at org.spockframework.mock.runtime.JavaMockFactory.create(JavaMockFactory.java:42)
	at org.spockframework.mock.runtime.CompositeMockFactory.create(CompositeMockFactory.java:44)
	at org.spockframework.lang.SpecInternals.createMock(SpecInternals.java:55)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:330)
	at org.spockframework.lang.SpecInternals.createMockImpl(SpecInternals.java:320)
	at org.spockframework.lang.SpecInternals.MockImpl(SpecInternals.java:123)
	at apackage.ASpec.a feature(Script_2ea152aea2eb5fd1885101de83bd8e60.groovy:1)
Caused by: java.lang.NoClassDefFoundError: foo/Bar
	at java.base/java.lang.System$2.defineClass(System.java:2394)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$Dispatcher$ForNonStaticMethod.invoke(JavaDispatcher.java:1033)
	at net.bytebuddy.utility.dispatcher.JavaDispatcher$ProxiedInvocationHandler.invoke(JavaDispatcher.java:1163)
	at net.bytebuddy.dynamic.loading.ClassInjector$UsingLookup.injectRaw(ClassInjector.java:1639)
	at net.bytebuddy.dynamic.loading.ClassInjector$AbstractBase.inject(ClassInjector.java:119)
	at net.bytebuddy.dynamic.loading.ClassLoadingStrategy$UsingLookup.load(ClassLoadingStrategy.java:519)
	at net.bytebuddy.dynamic.TypeResolutionStrategy$Passive.initialize(TypeResolutionStrategy.java:101)
	at net.bytebuddy.dynamic.DynamicType$Default$Unloaded.load(DynamicType.java:6367)
	at org.spockframework.mock.runtime.ByteBuddyMockFactory.lambda$createMock$2(ByteBuddyMockFactory.java:137)
	at net.bytebuddy.TypeCache.findOrInsert(TypeCache.java:168)
	... 16 more
Caused by: java.lang.ClassNotFoundException: foo.Bar
	at java.base/java.lang.ClassLoader.findClass(ClassLoader.java:733)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:593)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526)
	... 26 more
```

</details>

Spock will pick the ByteBuddy MockMaker and then use the `net.bytebuddy.dynamic.loading.ClassLoadingStrategy.UsingLookup` classloading strategy. This strategy receives the lookup of the to-be-mocked class. It then uses that lookup to define the mocked class. Internally, this just means that the classloader of the to-be-mocked is used. In our example, this would be `MockedClassClassLoader`. This classloader is not able to see `foo.Bar` and therefore loading the mocked class fails.

### To Reproduce

Paste the following testcase in `spock.util.EmbeddedSpecRunnerClassLoaderSpec`:

```groovy
  def "ByteBuddy Mocks with interfaces that are not visible to the mocked type's classloader"() {
    def testCl1 = new ByteBuddyTestClassLoader()
    def testCl2 = new ByteBuddyTestClassLoader()
    testCl1.defineInterface("foo.Bar")
    testCl2.defineClass("iam.Mocked")
    def cl = new MultipleParentClassLoader([getClass().classLoader, testCl1, testCl2])
    def runner = new EmbeddedSpecRunner(cl)
    when:
    def r = runner.runFeatureBody("""
def mock = Mock(iam.Mocked, additionalInterfaces: [foo.Bar])
expect:
true
""")
    then:
    noExceptionThrown()
  }
```

and run `gradlew :spock-specs:test --tests "spock.util.EmbeddedSpecRunnerClassLoaderSpec.ByteBuddy Mocks with interfaces that are not visible to the mocked type's classloader" "-Dvariant=4.0" "-DjavaVersion=21"`

### Expected behavior

The mocking succeeds

### Actual behavior

See exception above

### Java version

openjdk version "21.0.2" 2024-01-16

### Buildtool version

Gradle 8.10.2

### What operating system are you using

Windows

### Dependencies

Reproducer works in spock repo

### Additional context

Mockito has a similar problem. They only use the Lookup strategy for "local mocks" (see [here](https://github.com/mockito/mockito/blob/99426415c0ceb30e55216c3934854528c83f410e/mockito-core/src/main/java/org/mockito/internal/creation/bytebuddy/SubclassBytecodeGenerator.java#L165-L166)). Local mocks are mocks where the mocked type and all its additional interfaces are loadable by the classloader of the mocked type. I'd suggest implementing the same behavior for Spock and falling back to another loading strategy for non-local mocks. I have a simple version of this change ready and would love to open a PR if we can agree on this solution :)

Also FYI: I discovered this bug together with @AndreasTu

### PR DESCRIPTION
**Pull request by beatbrot**
ByteBuddy: Do not use Lookup for non-local mocks

This PR introduces the concept of local mocks. A mock is considered to be local if the target class' classloader can also load all additional interfaces (incl. `ISpockMockObject`).

The lookup classloading strategy may only be used if a mock is local.
Otherwise we have to defer to other strategies.

Fixes #2017

### CODE REVIEW

File: spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockMakerSpec.groovy [hunk 1]
```diff
@@ -150,6 +153,36 @@ class ByteBuddyMockMakerSpec extends Specification {
     CannotCreateMockException ex = thrown()
     ex.message.startsWith("Cannot create mock for interface java.lang.Runnable. byte-buddy: The class AdditionalInterface is not visible by the classloader")
   }
+
+  def "ByteBuddy Mocks with interfaces that are not visible to the mocked type's classloader"() {
```
Comment (AndreasTu) [inline spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockMakerSpec.groovy:157]: Please add an `@Issue()` annotation with a full link to the github issue.

File: spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockMakerSpec.groovy [hunk 2]
```diff
@@ -150,6 +153,36 @@ class ByteBuddyMockMakerSpec extends Specification {
...
+    def testCl1 = new ByteBuddyTestClassLoader()
```
Comment (AndreasTu) [inline spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockMakerSpec.groovy:158]: Please add a `given:` label.

File: spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockMakerSpec.groovy [hunk 3]
```diff
@@ -150,6 +153,36 @@ class ByteBuddyMockMakerSpec extends Specification {
...
+    def testCl2 = new ByteBuddyTestClassLoader()
+    testCl1.defineInterface("foo.Bar")
+    testCl2.defineClass("iam.Mocked")
+    def cl = new MultipleParentClassLoader([getClass().classLoader, testCl1, testCl2])
+    def runner = new EmbeddedSpecRunner(cl)
+    when: "A type is mocked with an additional interface from a classloader outside the mocked type's parent chain"
```
Comment (AndreasTu) [inline spock-specs/src/test/groovy/org/spockframework/mock/runtime/ByteBuddyMockMakerSpec.groovy:164]: Please separate labels by a newline.

See [CONTRIBUTING Guide](https://github.com/spockframework/spock/blob/master/CONTRIBUTING.adoc#code-standards)

File: spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java [hunk 4]
```diff
@@ -83,6 +83,26 @@ class ByteBuddyMockFactory {
     }
   }
 
+  /**
+   * {@return true, if the mock is considered local}
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java:87]: This syntax seams strange.
Shouldn't the `@return` a the parameters without the `{}`?

File: spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java [hunk 5]
```diff
@@ -83,6 +83,26 @@ class ByteBuddyMockFactory {
     }
   }
 
+  /**
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java:86]: Could you please add a line in the `2.4 (tdb) Misc` section that the issue #2017 was fixed.

See file: `docs/release_notes.adoc`

File: spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java [hunk 6]
```diff
@@ -83,6 +83,26 @@ class ByteBuddyMockFactory {
...
+   * A mock is considered local, if all additional interfaces of the mock (including {@link ISpockMockObject}) are
+   * loadable by the target class' classloader.
+   *
+   * @param targetClass The to-be-mocked class
+   * @param additionalInterfaces Additional interfaces of the to-be-mocked type
+   */
+  @VisibleForTesting
+  static boolean isLocalMock(Class<?> targetClass, Collection<Class<?>> additionalInterfaces) {
+    // Inspired by https://github.com/mockito/mockito/blob/99426415c0ceb30e55216c3934854528c83f410e/mockito-core/src/main/java/org/mockito/internal/creation/bytebuddy/SubclassBytecodeGenerator.java#L165-L166
+    ClassLoader cl = new MultipleParentClassLoader.Builder()
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java:98]: I would expect that you use the constructed `cl` here also as `classLoader` in line 142, if `cl != classloader`.

I your solution you "create" two classloaders, because if `cl!= classloader` then bytebuddy need to do the same sthing again.
See mockito code, which also uses the contructed classloader in that case.

Maybe change the signature to return the `cl` and then you can test against it.

**Review by AndreasTu — CHANGES_REQUESTED** [review]
Thank you for your PR!

File: spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java (hunk 4 above)
Comment (beatbrot) [reply spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java:87]: Yeah thats a Java 16 feature. Forgot that we are targeting 8 here, so I'll change it :)

File: spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java (hunk 6 above)
Comment (beatbrot) [reply spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java:98]: I initially opted against this, since this basically introduces another classloading strategy.

The thing I wanted to introduce was "let's gracefully fall back to the next best strategy if the Lookup strategy won't work".
Your proposal would be "Lets introduce a new strategy that is only used if the Lookup strategy is wrongfully selected and turns out to not work".

The fact that ByteBuddy would currently do the same as me is merely an implementation detail in the current version.

Imo my solution keeps the complexity lower at the small cost of an unneeded classloader construction. If you still prefer your solution, I can change the code :)

Comment (AndreasTu) [reply spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java:99]: No I think your reasoning is fine. You can leave it as it is.

**Review by AndreasTu — APPROVED** [review]

**Comment by AndreasTu** [comment]
@beatbrot Thank you very much for your contribution!
I would like to wait with the merge to give @leonard84 time to respond, if he has any comments about this PR.

**Review by leonard84 — APPROVED** [review]
