### PR TITLE
ByteBuddyMockFactory adds `@Internal` annotation to Groovy MOP methods

### LINKED ISSUE #1501: Unable to access protected constant when spying instances
### Problem
I have a test that spies an instance:

```
private MainKnowledgeSessionService service

    void setup() {
        service = new MainKnowledgeSessionService()
        
        [... hidden code for clarity...]
    }

    @Unroll
    void "test"() {
        given: "an spy of the service"
        MyService spiedService = Spy(service)

        when:
        spiedService.runMethod(param)
        
        then:
        true
    }
```
The service class that I’m spying is defined in groovy as _MyService.groovy_ as this:

```
@Transactional
@Service
class MyService extends ParentService {
  [... hidden code for clarity...]
}
```
The parent service is defined in java as _ParentService.java_ as this:

```
public abstract class ParentService {

    protected static final boolean MONITOR_ENABLED = LoggerFactory.getLogger(ParentService.class).isDebugEnabled();
```
As you can see the constant _MONITOR_ENABLED_ is protected so it is accesible from the _MyService_ class.

But, when I run the test, in some part of the _MyService_ I execute this block of code:

```
if (MONITOR_ENABLED) {
    // whatever
}
```
Then, I that point, the tests is failing with this error:

```
No signature of method: com.foo.services.MyService.getMONITOR_ENABLED() is applicable for argument types: () values: []
groovy.lang.MissingMethodException: No signature of method: com.foo.services.MyService.getMONITOR_ENABLED() is applicable for argument types: () values: []
```
Why Groovy is asking me for a getter when the constant is accesible from the _MyService_ class?

### Cause
We did a bit of research debugging the creation of a spy using Spock and we founded that in the method org.spockframework.mock.runtime.JavaMockFactory#createInternal we are generating a proxy class and copying the fields from the instance class to the proxy class

```
private Object createInternal(IMockConfiguration configuration, Specification specification, ClassLoader classLoader) {
    if (Modifier.isFinal(configuration.getType().getModifiers())) {
      throw new CannotCreateMockException(configuration.getType(),
          " because Java mocks cannot mock final classes. If the code under test is written in Groovy, use a Groovy mock.");
    }
    if (configuration.isGlobal()) {
      throw new CannotCreateMockException(configuration.getType(),
          " because Java mocks cannot mock globally. If the code under test is written in Groovy, use a Groovy mock.");
    }

    MetaClass mockMetaClass = GroovyRuntimeUtil.getMetaClass(configuration.getType());
    IProxyBasedMockInterceptor interceptor = new JavaMockInterceptor(configuration, specification, mockMetaClass);
    Object proxy = ProxyBasedMockFactory.INSTANCE.create(configuration.getType(), configuration.getAdditionalInterfaces(),
      configuration.getConstructorArgs(), interceptor, classLoader,
      configuration.isUseObjenesis());
    if ((configuration.getNature() == MockNature.SPY) && (configuration.getInstance() != null)) {
      ReflectionUtil.deepCopyFields(configuration.getInstance(), proxy);
    }
    return proxy;
  }
```
Then, we compared the metaclass field of the proxy instance generated between  Groovy 2.4.21 and Groovy 3.0.10 and these are the differences:

Groovy 2
image

Groovy 3
image

As you can see, there is a new property at CacheField class that is called madeAccessible that is set to false using Groovy 3. 

### To Reproduce

Create a test that spies an instance:

```
private MyService service

    void setup() {
        service = new MyService()
        
        [... hidden code for clarity...]
    }

    @Unroll
    void "test"() {
        given: "an spy of the service"
        MyService spiedService = Spy(service)

        when:
        spiedService.runMethod(param)
        
        then:
        true
    }
```

Create a service class defined in groovy as _MyService.groovy_ as this:

```
class MyService extends ParentService {
  public runMethod() {
if (MONITOR_ENABLED) {
    println "Well done!"
}
}
}
```

Create parent service in java as _ParentService.java_ as this:

```
public abstract class ParentService {

    protected static final boolean MONITOR_ENABLED = true;
```
Run the test and check that is free of exceptions and pass.

### Expected behavior

The protected constant should be accesible from the child class since it is protected.

### Actual behavior

The constant is not accessible and we have getting the error 

```
No signature of method: com.foo.services.MyService.getMONITOR_ENABLED() is applicable for argument types: () values: []
groovy.lang.MissingMethodException: No signature of method: com.foo.services.MyService.getMONITOR_ENABLED() is applicable for argument types: () values: []
```

### Java version

openjdk version "1.8.0_332"
OpenJDK Runtime Environment (Zulu 8.62.0.19-CA-linux64) (build 1.8.0_332-b09)
OpenJDK 64-Bit Server VM (Zulu 8.62.0.19-CA-linux64) (build 25.332-b09, mixed mode)

### Buildtool version

------------------------------------------------------------
Gradle 6.9.2
------------------------------------------------------------

Build time:   2021-12-21 20:18:38 UTC
Revision:     5d94aa68c0fdbe443838bb977080e3b9f273e889

Kotlin:       1.4.20
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.9 compiled on September 27 2020
JVM:          1.8.0_332 (Azul Systems, Inc. 25.332-b09)
OS:           Linux 5.15.0-41-generic amd64

### What operating system are you using

Linux

### Dependencies

+--- org.codehaus.groovy:groovy:3.0.10
+--- org.codehaus.groovy:groovy-all:3.0.10 (*)
+--- org.spockframework:spock-core:2.1-groovy-3.0
|    +--- org.codehaus.groovy:groovy:3.0.9 -> 3.0.10
|    +--- org.junit.platform:junit-platform-testkit -> 1.8.2
|    |    +--- org.junit:junit-bom:5.8.2 (*)
|    |    +--- org.assertj:assertj-core:3.20.2 -> 3.22.0
|    |    +--- org.opentest4j:opentest4j:1.2.0
|    |    \--- org.junit.platform:junit-platform-launcher:1.8.2 (*)
|    +--- org.jetbrains:annotations:20.1.0
|    +--- org.ow2.asm:asm:9.2
|    +--- net.bytebuddy:byte-buddy:1.12.1 -> 1.12.11
|    +--- cglib:cglib-nodep:3.3.0
|    +--- org.objenesis:objenesis:3.2
|    +--- org.junit:junit-bom:5.8.1 -> 5.8.2 (*)
|    +--- org.junit.platform:junit-platform-engine -> 1.8.2 (*)
|    \--- org.hamcrest:hamcrest:2.2
+--- org.objenesis:objenesis:3.2
+--- org.springframework.boot:spring-boot-starter-test -> 2.7.1
|    +--- org.springframework.boot:spring-boot-starter:2.7.1 (*)
|    +--- org.springframework.boot:spring-boot-test:2.7.1
|    |    \--- org.springframework.boot:spring-boot:2.7.1 (*)
|    +--- org.springframework.boot:spring-boot-test-autoconfigure:2.7.1
|    |    +--- org.springframework.boot:spring-boot:2.7.1 (*)
|    |    +--- org.springframework.boot:spring-boot-test:2.7.1 (*)
|    |    \--- org.springframework.boot:spring-boot-autoconfigure:2.7.1 (*)
|    +--- com.jayway.jsonpath:json-path:2.7.0
|    |    +--- net.minidev:json-smart:2.4.7 -> 2.4.8
|    |    |    \--- net.minidev:accessors-smart:2.4.8
|    |    |         \--- org.ow2.asm:asm:9.1 -> 9.2
|    |    \--- org.slf4j:slf4j-api:1.7.33 -> 1.7.36
|    +--- jakarta.xml.bind:jakarta.xml.bind-api:2.3.3 (*)
|    +--- org.assertj:assertj-core:3.22.0
|    +--- org.hamcrest:hamcrest:2.2
|    +--- org.junit.jupiter:junit-jupiter:5.8.2
|    |    +--- org.junit:junit-bom:5.8.2 (*)
|    |    +--- org.junit.jupiter:junit-jupiter-api:5.8.2 (*)
|    |    +--- org.junit.jupiter:junit-jupiter-params:5.8.2
|    |    |    +--- org.junit:junit-bom:5.8.2 (*)
|    |    |    \--- org.junit.jupiter:junit-jupiter-api:5.8.2 (*)
|    |    \--- org.junit.jupiter:junit-jupiter-engine:5.8.2 (*)
|    +--- org.mockito:mockito-core:4.5.1 -> 2.23.4
|    |    +--- net.bytebuddy:byte-buddy:1.9.3 -> 1.12.11
|    |    +--- net.bytebuddy:byte-buddy-agent:1.9.3 -> 1.12.11
|    |    \--- org.objenesis:objenesis:2.6 -> 3.2
|    +--- org.mockito:mockito-junit-jupiter:4.5.1
|    |    +--- org.mockito:mockito-core:4.5.1 -> 2.23.4 (*)
|    |    \--- org.junit.jupiter:junit-jupiter-api:5.8.2 (*)
|    +--- org.skyscreamer:jsonassert:1.5.0
|    +--- org.springframework:spring-core:5.3.21 (*)
|    +--- org.springframework:spring-test:5.3.21 (*)
|    \--- org.xmlunit:xmlunit-core:2.9.0
+--- com.shazam:shazamcrest:0.7
|    +--- org.skyscreamer:jsonassert:1.2.0 -> 1.5.0
|    +--- com.google.code.gson:gson:2.2.4 -> 2.8.9
|    +--- junit:junit:4.11 -> 4.13.1 (*)
|    \--- org.apache.commons:commons-lang3:3.1 -> 3.8.1
+--- org.hamcrest:hamcrest-all:1.3
+--- org.mockito:mockito-core:2.23.4 (*)
+--- org.hamcrest:hamcrest-library:1.3
|    \--- org.hamcrest:hamcrest-core:1.3 -> 2.2 (*)
+--- com.tngtech.archunit:archunit:0.16.0
|    \--- org.slf4j:slf4j-api:1.7.30 -> 1.7.36

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by AndreasTu**
The Groovy 3 & 4 runtime expects to have the `@Internal` annotation on the MOP methods from `GroovyObject`. That `AbstractCallSite.createGroovyObjectGetPropertySite()` processes it as `GroovyObject`. So the `ByteBuddyMockFactory` now adds the `@Internal` annotation to the intercepted MOP methods.

After that the "Unable to access protected constant when spying instances" problems are gone, because we take the normal Groovy route.

Also some strange inconsistencies for Groovy  2 <=> 3,4 are now gone, but a new inconsistency appeared Groovy 4 prefers is over get for boolean. But this is not a Spock issue, because in Groovy only code the same thing happens. See tests in JavaMocksForGroovyClasses.

This fixes #1501, #1452, #1608 and #1145.

### CODE REVIEW

File: spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaMocksForGroovyClasses.groovy [hunk 1]
```diff
@@ -271,21 +259,59 @@ class JavaMocksForGroovyClasses extends Specification {
...
     1 * mockData.getActive() >> true
     0 * mockData.isActive()
 
     and:
     result == "Data is current"
   }
 
+  /**
+   * The resolution of properties changed in Groovy 4 for the ExampleData.active Groovy 4 resolves the is
+   * whereas Groovy 2 & 3 resolved the get.
```
Comment (leonard84) [inline spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaMocksForGroovyClasses.groovy:280]:
```suggestion
   * The resolution of properties changed in Groovy 4 for the ExampleData.active Groovy 4 resolves the 'is'
   * whereas Groovy 2 & 3 resolved the 'get'.
```

**Review by leonard84 — CHANGES_REQUESTED** [review]
Thanks, just some small changes

File: spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy [hunk 2]
```diff
@@ -0,0 +1,81 @@
+package org.spockframework.mock
+
+import org.spockframework.runtime.model.parallel.ExecutionMode
+import spock.lang.Execution
+import spock.lang.Issue
+import spock.lang.Specification
+
+@Execution(ExecutionMode.SAME_THREAD)
```
[the remark this answers is not in the document]
Comment (AndreasTu) [reply spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy:8]: I have added this to ensure execution order, because if the test `"Access protected fields via access methods without spy"` runs before the `"Access protected const should be accessible in Groovy 3&4 Issue #1501"` the second test would not fail without the fix, because the MetaClass in Groovy was already initialized and pointing to the correct property. Shall I add a comment to that to clarifiy this.

File: spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaMocksForGroovyClasses.groovy [hunk 3]
```diff
@@ -271,21 +259,59 @@ class JavaMocksForGroovyClasses extends Specification {
...
+    !data.active //The isActive() method returns false
+  }
+
+  @Requires({ GroovyRuntimeUtil.isGroovy3orOlder() })
+  def "Real object boolean (get + is) accessor via dot-notation (Groovy 2&3)"() {
+    given:
+    def data = new ExampleData()
+    expect:
+    data.active //The getActive() method returns true
+  }
```
[the remark this answers is not in the document]
Comment (AndreasTu) [reply spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaMocksForGroovyClasses.groovy]: Done

File: spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java [hunk 4]
```diff
@@ -30,6 +34,10 @@ class ByteBuddyMockFactory {
     new TypeCache.WithInlineExpunction<>(TypeCache.Sort.SOFT);
   private static final Class<?> CODEGEN_TARGET_CLASS = Target.class;
   private static final String CODEGEN_PACKAGE = CODEGEN_TARGET_CLASS.getPackage().getName();
+  @Nullable
+  private static final AnnotationDescription INTERNAL_ANNOTATION = ReflectionUtil.isClassAvailable("groovy.transform.Internal") ?
+    AnnotationDescription.Builder.ofType(Internal.class).build() : null;
```
[the remark this answers is not in the document]
Comment (AndreasTu) [reply spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java]: I have removed the `ReflectionUtil.isClassAvailable()` check.

[the remark this answers is not in the document]
Comment (leonard84) [reply spock-core/src/main/java/org/spockframework/mock/runtime/ByteBuddyMockFactory.java]: > I was not sure, if we still want to support Groovy < 2.5.

We don't 2.5 is the lowest version we support.

File: spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy (hunk 2 above)
[the remark this answers is not in the document]
Comment (leonard84) [reply spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy:8]: If the order is important then `@Stepwise` seems to be the better choice.

File: spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy [hunk 5]
```diff
@@ -0,0 +1,85 @@
...
+class AccessProtectedPropsSpec extends Specification {
+
+  /**
+   * The problem with https://github.com/spockframework/spock/issues/1501 is that the ByteBuddyMockFactory overrides
+   * the <code>getProperty(String)</code> method from GroovyObject without having the <code>groovy.transform.Internal</code>
```
Comment (leonard84) [inline spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy:13]: Isn't the `{@code method()}` syntax preferable?

File: spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaMocksForGroovyClasses.groovy [hunk 6]
```diff
@@ -271,21 +259,59 @@ class JavaMocksForGroovyClasses extends Specification {
...
+    and:
+    result == "Data is current"
+  }
+
+  @Requires({ GroovyRuntimeUtil.isGroovy3orOlder() })
+  def "Real object boolean (get + is) accessor via dot-notation (Groovy 2&3)"() {
+    given:
+    def data = new ExampleData()
+    expect:
+    data.active //The getActive() method returns true
```
Comment (leonard84) [inline spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaMocksForGroovyClasses.groovy:304]:
```suggestion
    expect: 'the getActive() method returns true'
    data.active
```

File: spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaMocksForGroovyClasses.groovy [hunk 7]
```diff
@@ -271,21 +259,59 @@ class JavaMocksForGroovyClasses extends Specification {
...
+  }
+
+  @Requires({ GroovyRuntimeUtil.isGroovy4orNewer() })
+  def "Real object boolean (get + is) accessor via dot-notation (Groovy 4)"() {
+    given:
+    def data = new ExampleData()
+    expect:
+    !data.active //The isActive() method returns false
```
Comment (leonard84) [inline spock-specs/src/test/groovy/org/spockframework/smoke/mock/JavaMocksForGroovyClasses.groovy:312]:
```suggestion
    expect: 'the isActive() method returns false'
    !data.active 
```

**Review by leonard84 — CHANGES_REQUESTED** [review]

**Review by Vampire — CHANGES_REQUESTED** [review]
You mentioned this will fix #1608, but no `@Issue` mentions it.
If an already existing test covers it, please add a second `@Issue` annotation, if not please add a test for that case.

File: spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy [hunk 8]
```diff
@@ -0,0 +1,102 @@
...
+   * The problem with https://github.com/spockframework/spock/issues/1501 is that the ByteBuddyMockFactory overrides
+   * the {@code getProperty(String)} method from GroovyObject without having the {@code groovy.transform.Internal}
+   * annotation. Therefore {@code org.codehaus.groovy.runtime.callsite.AbstractCallSite.createGroovyObjectGetPropertySite(java.lang.Object)}
+   * takes another code path.
+   */
+  @Issue("https://github.com/spockframework/spock/issues/1501")
+  @Issue("https://github.com/spockframework/spock/issues/1608")
+  def "Access protected const should be accessible in Groovy 3&4 Issue #1501"() {
+    when:
+    AccessProtectedSubClass mySpy = Spy(AccessProtectedSubClass)
```
Comment (Vampire) [inline spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy:36]:
```suggestion
    AccessProtectedSubClass mySpy = Spy()
```

File: spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy [hunk 9]
```diff
@@ -0,0 +1,102 @@
...
+    then:
+    mySpy.accessStaticFlag()
+  }
+
+  @Issue("https://github.com/spockframework/spock/issues/1501")
+  @Issue("https://github.com/spockframework/spock/issues/1608")
+  def "Access protected should be accessible in Groovy 3&4 Issue #1501"() {
+    when:
+    AccessProtectedSubClass mySpy = Spy(AccessProtectedSubClass)
```
Comment (Vampire) [inline spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy:45]:
```suggestion
    AccessProtectedSubClass mySpy = Spy()
```

File: spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy [hunk 10]
```diff
@@ -0,0 +1,102 @@
...
+  /**
+   * This feature must run after the {@code Access protected const should be accessible in Groovy 3&4 Issue #1501},
+   * otherwise the MetaClass gets cached in the GroovyRuntime, therefore we need the {@code @Stepwise}.
+   */
+  def "Access protected fields via access methods without spy"() {
+    when:
+    AccessProtectedSubClass mySpy = new AccessProtectedSubClass()
+    then:
+    mySpy.accessNonStaticFlag()
+    mySpy.accessStaticFlag()
```
Comment (Vampire) [inline spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy:59]:
```suggestion
    AccessProtectedSubClass myNonSpy = new AccessProtectedSubClass()
    then:
    myNonSpy.accessNonStaticFlag()
    myNonSpy.accessStaticFlag()
```

File: spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy [hunk 11]
```diff
@@ -0,0 +1,102 @@
...
+  }
+
+  @Issue("https://github.com/spockframework/spock/issues/1501")
+  def "Access protected fields should be accessible in Groovy 3&4 with Java class Issue #1501"() {
+    when:
+    AccessProtectedJavaSubClass mySpy = Spy(AccessProtectedJavaSubClass)
```
Comment (Vampire) [inline spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy:65]:
```suggestion
    AccessProtectedJavaSubClass mySpy = Spy()
```

File: spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy [hunk 12]
```diff
@@ -0,0 +1,102 @@
...
+    then:
+    mySpy.accessNonStaticFlag()
+  }
+
+  @Issue("https://github.com/spockframework/spock/issues/1452")
+  def "Access protected fields Issue #1452"() {
+    when:
+    AccessProtectedSubClass mySpy = Spy(AccessProtectedSubClass)
```
Comment (Vampire) [inline spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy:73]:
```suggestion
    AccessProtectedSubClass mySpy = Spy()
```

File: spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy [hunk 13]
```diff
@@ -0,0 +1,102 @@
...
+    mySpy.nonStaticFlag
+    mySpy.staticFlag
+  }
+
+  def "Access protected fields without spy"() {
+    when:
+    AccessProtectedSubClass mySpy = new AccessProtectedSubClass()
+    then:
+    mySpy.nonStaticFlag
+    mySpy.staticFlag
```
Comment (Vampire) [inline spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedPropsSpec.groovy:84]:
```suggestion
    AccessProtectedSubClass myNonSpy = new AccessProtectedSubClass()
    then:
    myNonSpy.nonStaticFlag
    myNonSpy.staticFlag
```

File: spock-specs/src/test/groovy/org/spockframework/mock/MockMapDelegateSpec.groovy [hunk 14]
```diff
@@ -0,0 +1,42 @@
...
+
+import spock.lang.Issue
+import spock.lang.Specification
+
+class MockMapDelegateSpec extends Specification {
+
+  @Issue("https://github.com/spockframework/spock/issues/1145")
+  def "Mock a Map delegate Issue #1145"() {
+    given:
+    def ctx = Mock(MapDelegate)
```
Comment (Vampire) [inline spock-specs/src/test/groovy/org/spockframework/mock/MockMapDelegateSpec.groovy:27]:
```suggestion
    MapDelegate ctx = Mock()
```

File: spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedJavaBaseClass.java
Comment (Vampire) [inline spock-specs/src/test/groovy/org/spockframework/mock/AccessProtectedJavaBaseClass.java:1]: Java class should be in Java source set. :-)

**Review by Vampire — CHANGES_REQUESTED** [review]
The more often I look, the more I find. 🙈

**Review by Vampire — APPROVED** [review]
LGTM, thx

**Review by leonard84 — APPROVED** [review]

**Comment by leonard84** [comment]
Thanks @AndreasTu
