### PR TITLE
GenericTypeReflectorUtil.getReturnType() now resolves type variables

### LINKED ISSUE #520: Better support for generic return types with Stub()
I'm seeing some regression issues when upgrading to spock 1.0.
Consider the following:

``` java
interface Repository {
    <E extends Object, ID extends Serializable> ID persist(E e);
}
class MagicWand {
    private Repository repository;
    public MagicWand(Repository repository) {
        this.repository = repository;
    }
    Long wave(Object o) {
        repository.persist(o);
        return 42L;
    }
}
```

And spec:

``` groovy
class MagicWandSpec extends Specification {
    MagicWand wand = new MagicWand(Stub(Repository))
    def testGenerics() {
        expect:
            wand.wave(55L) == 42L
    }
}
```

jdk8 plus 0.7-groovy-2.0 - _PASS_
jdk8 plus 1.0-groovy-2.4 - _FAIL_:

```
java.lang.ClassCastException: java.lang.Object cannot be cast to java.io.Serializable
```

### LINKED ISSUE #1163: NodeInfo#getAnnotation returns instance of Cglib-generated that does not actually implement Annotation
# Issue description

`org.spockframework.runtime.model.NodeInfo#getAnnotation` returns an instance of a generated class which is not implementing `Annotation`, hence it doesn't actually work when it's used as a `ClassCastException` is thrown.

# How to reproduce

In a Spock extension, call `getAnnotation` on a `SpecInfo` instance as shown:

```groovy
Title t = node.getAnnotation( Title )
```

This error will happen (when there's no annotation on the spec, at least):

```
org.spockframework.runtime.model.SpecInfo$$EnhancerByCGLIB$$b2e871b8 cannot be cast to java.lang.annotation.Annotation
```

I would've expected `null` to be returned and there should be no error.

## Java/JDK

```
openjdk version "1.8.0_232"
```

## Groovy version

* Groovy 3.0.1
* Spock 2.0-M2-groovy-3.0

### PR DESCRIPTION
**Pull request by AndreasTu**
The method `GenericTypeReflectorUtil.getReturnType()` now also tries to resolve TypeVariable, if these have bounds like the method:

`<T extends Annotation> T getAnnotation()`

Which now returns `Annotation` as return type instead of `Object`.

This was actually implemented with:
Replace gentyref code with geantyref library #1743.

This fixes #1163 "NodeInfo#getAnnotation returns instance of Cglib-generated that does not actually implement Annotation".
It also fixes #520 "Better support for generic return types with Stub()".

### CODE REVIEW

**Comment by leonard84** [comment]
The gentyref code we have is copied from a project and quite old. There is a successor project https://github.com/leangen/geantyref that has many changes, improvements, and fixes, but it wasn't straight forward drop-in update as some checks were stricter and broke some existing code. Would you be willing to look into updating this whole part? 
Not in this PR, but in a followup.

**Comment by AndreasTu** [comment]
@leonard84 Yes sure I can give it a shot.
Do you want to then clone it into the code base again, or use it as a library?

**Comment by AndreasTu** [comment]
@leonard84 #1743 replaces `gentyref` with [geantyref](https://github.com/leangen/geantyref).

**Comment by leonard84** [comment]
@AndreasTu #1743 has been merged, can you rebase and resolve the conflicts?

**Comment by AndreasTu** [comment]
@leonard84 done

File: spock-specs/src/test/groovy/org/spockframework/mock/Issue520Repository.java [hunk 1]
```diff
@@ -0,0 +1,9 @@
+package org.spockframework.mock;
+
+import java.io.Serializable;
+
+public interface Issue520Repository {
+  //Note: we need to compile this with Java, because Groovy 2.5 can't compile this:
+  //unexpected token: <E extends Object, ID extends Serializable> ID persist(E e);
+  <E extends Object, ID extends Serializable> ID persist(E e);
```
Comment (leonard84) [inline spock-specs/src/test/groovy/org/spockframework/mock/Issue520Repository.java:8]: It can actually if you place a `def` in front, it looks wrong but it works.

**Review by leonard84 — APPROVED** [review]
So it works OOTB with geantyref, or did you add the necessary change already in that commit?

**Comment by AndreasTu** [comment]
I added the required changes in #1743 it is in the `GenericTypeReflectorUtil.resolveTypeVariableWithBound()`.
