### PR TITLE
Properly fix possible deadlock, when blocking in mock response generators and fix fallout of #1885 (#583, #1899)

### LINKED ISSUE #583: Concurrent interactions deadlock because of a synchronized method MockController#handle
The version is 1.0-groovy-2.4

``` groovy
import spock.lang.Specification

import java.util.concurrent.CountDownLatch
import java.util.concurrent.Semaphore

class CodeRunnerSpec extends Specification {

    class CodeRunner {

        Runnable code

        Runnable fallback

        Semaphore semaphore = new Semaphore(1)

        void log(String message) {
            println Thread.currentThread().getName() + ' ' + message
        }

        /**
         * Runs the runnable in a new (!) thread. 
         * If the runnable is already running, runs fallback in the current (!) thread
         */
        void runCode() {

            log '=== runCode(): begin ===' 
            log 'trying to acquire the semaphore'

            if (semaphore.tryAcquire()) {

                log 'starting the code in a new thread'

                Thread.start {

                    log 'we are in the thread, starting the code'

                    code.run()

                    log 'code has finished working, releasing the semaphore'

                    semaphore.release()
                }

                log 'the thread has been started'

            } else {

                log 'the semaphore is busy, running the fallback'

                fallback.run()

                log 'the fallback has finished'
            }

            log '=== runCode(): end ==='
        }
    }

    def "Should run the fallback the code is already running"() {

        given:

        CountDownLatch latch = new CountDownLatch(1)

        CodeRunner codeRunner = new CodeRunner();

        codeRunner.code = Stub(Runnable) {
            run() >> {
                codeRunner.log 'waiting...'
                latch.await()
                codeRunner.log 'finished waiting, exiting'
            }
        }

        codeRunner.fallback = Mock(Runnable)

        when:

        // the closure will start in a new (!) thread and start to wait on the latch
        codeRunner.runCode()

        Thread.sleep(10)

        // the closure is already running, so the fallback should be run in the current (!) thread
        codeRunner.runCode()

        ///////////////////////////////////////////////////////////////////////////////////
        // it won't get to here, as it will be waiting on entering a synchronized method:
        //
        //          org.spockframework.mock.runtime.MockController#handle
        //
        ///////////////////////////////////////////////////////////////////////////////////

        then:

        1 * codeRunner.fallback.run()

        cleanup:

        latch.countDown()
    }
}
```

### PR DESCRIPTION
**Pull request by Vampire**
This PR reverts the changes of PR #1885 and hopefully fixes #583, #1882, and #1899 properly
without the fallout of the previous PR.
All interaction handling stays synchronized, but the response generation happens unsynchronized.

As said in #1885, I think this should immediately be released as 2.4-M3 if it passes review as in M2 the whole interaction handling is highly broken in any multi-threaded situation.

### CODE REVIEW

File: spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy [hunk 1]
```diff
@@ -2,33 +2,60 @@ package org.spockframework.smoke.mock
...
+    given:
+    def called = false
+    Runnable foo
+    foo = Mock {
+      run() >> {
+        if (!called) {
+          called = true
+          Thread.start { foo.run() }.join()
+        }
+      }
```
Comment (leonard84) [inline spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy:52]: I think this reads better
```suggestion
    Runnable foo = Mock()
    foo.run() >> {
      if (!called) {
        called = true
        Thread.start { foo.run() }.join()
      }      
```

**Review by leonard84 — COMMENTED** [review]
Not sure if I'll have the time for a release before Sunday.

File: spock-core/src/main/java/org/spockframework/mock/runtime/InteractionScope.java [hunk 2]
```diff
@@ -40,26 +41,31 @@ public void addInteraction(final IMockInteraction interaction) {
...
-        Object result = null;
-        Throwable invocationException = null;
-        try {
-          result = super.accept(invocation);
-        } catch (AssertionError | Exception e) {
-          invocationException = e;
-        }
-        ExceptionUtil.throwWithSuppressed(invocationException, wrongInvocationOrderError);
-        return result;
+        Supplier<Object> supplierFromDecorated = super.accept(invocation);
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/mock/runtime/InteractionScope.java:57]: Can here any of the calls to `super.accept(invocation)` throw an exception, or assume that the internal supplier code do not throw an exception?
So is here an additional try/catch block missing?

File: spock-core/src/main/java/org/spockframework/mock/runtime/MockInteraction.java [hunk 3]
```diff
@@ -65,18 +66,16 @@ public boolean matches(IMockInvocation invocation) {
...
-      acceptedInvocations.add(invocation);
-      if (acceptedInvocations.size() > maxCount) {
-        throw new TooManyInvocationsError(this, acceptedInvocations);
-      }
-
-      return responseGenerator == null ? null : responseGenerator.respond(invocation);
-    } finally {
-      lock.writeLock().unlock();
+  public Supplier<Object> accept(IMockInvocation invocation) {
+    acceptedInvocations.add(invocation);
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/mock/runtime/MockInteraction.java:70]: Is it Ok to access and modify `acceptedInvocations` without holding any lock?
So is a `MockInteraction` thread-local?

File: spock-core/src/main/java/org/spockframework/mock/runtime/InteractionScope.java [hunk 4]
```diff
@@ -40,26 +41,31 @@ public void addInteraction(final IMockInteraction interaction) {
...
 
       @Override
-      public Object accept(IMockInvocation invocation) {
-        WrongInvocationOrderError wrongInvocationOrderError = null;
+      public Supplier<Object> accept(IMockInvocation invocation) {
+        WrongInvocationOrderError wrongInvocationOrderError;
         if (currentExecutionZone > myRegistrationZone) {
           wrongInvocationOrderError = new WrongInvocationOrderError(decorated, invocation, previousInvocationsInReverseOrder);
+        } else {
+          wrongInvocationOrderError = null;
```
[the remark this answers is not in the document]
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/mock/runtime/InteractionScope.java:49]: It is a necessity.
I use it in a lambda below, so it must be effectively final.
This  change achieves that.

File: spock-core/src/main/java/org/spockframework/mock/runtime/InteractionScope.java (hunk 2 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/mock/runtime/InteractionScope.java:57]: There should be no exception thrown.
At least no expected one.
I check through all `accept` methods we have and wrapped all code into the supplied, except for the state-changing code in `InteractionScope` and `MockInteraction` which should be done **within** the `synchronized` scope of the `MockController`.

Actually, in the current state the only think being delegated to here always is a `MockInteraction` anyway if I didn't miss something, so the only things it is doing is adding the invocation to the `acceptedInvocations` and checking the accepted count against the max count.

So I'd not expect any signifiant or important exceptions here and don't think an additional try/catch is necessary.

File: spock-core/src/main/java/org/spockframework/mock/runtime/MockInteraction.java (hunk 3 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/mock/runtime/MockInteraction.java:70]: It is not a thread-safe class, it is not thread-confined, and it is not safe to call `accept` without holding a lock.

The changes I made here are just rolling back the changes of the other PR, it was exactly like that before.

I marked the class as `@NotThreadSafe` explicitly now.
It could actually be made thread-safe lock-free simply by making the `acceptedInvocations` a `CopyOnWriteArraylist`.
Everything else is `final`, the `constraints` are effectively immutable, and all `responseGenerator`s are thread-safe now.

But the point is, that a `MockInteraction` instance is confined to a `MockController` and this `MockController` should only call methods on it while synchronizing on the mock controller to make sure the interaction matching and invocation counting is working properly, unlike with M2. So all accesses to `acceptedInvocations` actually **are** done under a lock, it just is external. So additionally making the class thread-safe could be done, but imho would just add unnecessary overhead, because it must anyway be used from synchronized blocks of `MockController` to ensure proper interaction matching and invocation counting.

The only thing where I'm not 100% sure is the `toString` method. This if called from a different thread could indeed show wrong values I think.

File: spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy [hunk 5]
```diff
@@ -2,33 +2,60 @@ package org.spockframework.smoke.mock
...
+
+    1 * aList.get(_) >> {
+      latch1.countDown()
+      assert latch2.await(10, SECONDS)
+    }
+
+    1 * aList.get(_) >> {
+      latch2.countDown()
+      assert latch1.await(10, SECONDS)
+    }
```
[the remark this answers is not in the document]
Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy:37]: Sure, why not, good idea 👌

File: spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy (hunk 1 above)
Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy:52]: Indeed

File: spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy (hunk 5 above)
[the remark this answers is not in the document]
Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy:37]: Too good idea. :-( This fails sometimes. I had it fail on 1. try, on 513. try, and on 82,643. try. :-/

I introduced another race condition when `SingleResponseGenerator.respond` is called outside of synchronization (as that is what would deadlock) but due to that now does set the `endOfCycle` too late, when before already the next interaction is requested from the response chain, so again the first response closure is returned, which then fails my improved test.

But if I do the `respond` call within the synchronization, response chain, then the two closures would again deadlock as long as they are in the same response chain.

Precalculating the value to be deliivered in the synchronization and then just returning it outside would not change anything, as the precalculating still means calling the closure.

Separating the `endOfCycle` modification out from `respond` might not work properly, as for the iterable response generator you can only ask the iterator for `hasNext` and that does not change unless you called `next()`. But calling `next` again is something that should not happen inside the synchronization as it could deadlock again.

🙈

[the remark this answers is not in the document]
Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy:37]: An alternative might be to just not support this within one response chain, but it would be nicer if it worked.
Because especially if an iterator is involved, you might not be able to split it into two iterations.

File: docs/release_notes.adoc [hunk 6]
```diff
@@ -5,6 +5,22 @@ include::include.adoc[]
 
 == 2.4 (tbd)
 
+=== Breaking Changes
+
+* Calculated responses for interactions (`>> { ... }`) previously were all executed synchronized on the respective mock
```
Comment (AndreasTu) [inline docs/release_notes.adoc:10]: Maybe add a link to the PR here somewhere `spockPull:1910[]`

**Review by AndreasTu — APPROVED** [review]

File: docs/release_notes.adoc (hunk 6 above)
Comment (Vampire) [reply docs/release_notes.adoc:10]: Yeah, always hard to do before the PR is created, as you don't know the number by then. :-D

File: spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy (hunk 5 above)
[the remark this answers is not in the document]
Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/smoke/mock/MultiThreaded.groovy:37]: Ok, having slept over it and brooded over it while working, I think I now properly solved it by adding yet another layer of indirection. :-D

At least the tests stayed green now the first 150_000 tries each. :-D

File: spock-core/src/main/java/org/spockframework/mock/IResponseGenerator.java [hunk 7]
```diff
@@ -16,10 +16,12 @@
...
 
+import java.util.function.Supplier;
+
 /**
  * Generates responses to mock invocations.
  */
 @Beta
 public interface IResponseGenerator {
-  Object respond(IMockInvocation invocation);
+  Supplier<Object> respond(IMockInvocation invocation);
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/mock/IResponseGenerator.java:26]: Shouldn't we add the supplier as default method and keep the old one?

```suggestion
  @Nullable
  default Object respond(IMockInvocation invocation) {
    return null;
  }
  
  /**
   * This method will be called by consumers.
   */
  default Supplier<Object> responseSupplier(IMockInvocation invocation) {
    return () -> respond(invocation); 
  }
```

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/mock/IResponseGenerator.java:26]: I'm not so sure how it is best.

We have basically 2 cases in 3rd party code.
1. someone is calling `respond`.
2. someone is implementing `respond`.

For code implementing respond, it would probably just work with your suggested change, as we use the `responseSupplier` which will call their `respond` method.

For code calling `respond`, for example like in `DetachedMockFactoryDocSpec` or `StaticSpyDocSpec`, with your suggested change it could get the wrong value as the `responseSupplier` is not used. Without your change already compiled code would fail as the signature changed. The code would actually still compile if just re-compiled but hopefully tests would recognize that behavior changed.

So maybe it is indeed beste to change it like you suggested and in those that really need the supplier to be used throw an exception in `respond`? This way existing code implementing `respond` would continue to work and code calling respond would work as long as they only call methods where it does not make a difference, but if they call one of the three where it makes a difference would get an exception and need to change their code.

What do you think?

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/mock/IResponseGenerator.java]: In case you started to look at the latest changes already, please do it again, sorry.
After having slept it over, I was unhappy with what I did yesterday and reworked it again.

File: spock-core/src/main/java/org/spockframework/mock/runtime/MockController.java [hunk 8]
```diff
@@ -38,31 +41,31 @@ public MockController() {
...
   public Object handle(IMockInvocation invocation) {
-    Optional<IMockInteraction> interaction = findInteraction(invocation);
-    if (interaction.isPresent()) {
-      try {
-        return interaction.get().accept(invocation);
-      } catch (InteractionNotSatisfiedError e) {
-        synchronized (this) {
-          errors.add(e);
+    Supplier<Object> resultSupplier = null;
+    synchronized (this) {
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/mock/runtime/MockController.java:45]: Why do you use a dedicated `LOCK` object in the other classes, but `this` here?

**Review by leonard84 — APPROVED** [review]

**Review by AndreasTu — DISMISSED** [review]

File: spock-core/src/main/java/org/spockframework/mock/runtime/MockController.java (hunk 8 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/mock/runtime/MockController.java:45]: Is it ok or do we need to change something?

**Review by leonard84 — APPROVED** [review]
