### PR TITLE
Fix extension-provided method arguments in fixture methods (#1305)

### LINKED ISSUE #1305: Method parameter injection into fixture methods is broken in 2.0
# Issue description

Gradle 7 will be available soon and relies on Groovy 3. As a maintainer of [gradle-node-plugin](https://github.com/node-gradle/gradle-node-plugin/), I tried to see if the project will build using Gradle 7.0-rc1. The plugin tests are based on Spock and there was a Groovy version conflict. It sounds like the only way to get the build work is to upgrade Spock to the 2.0 latest milestone. That's what I did and I encountered this issue.

We created an [extension](https://github.com/node-gradle/gradle-node-plugin/blob/master/src/test/groovy/com/github/gradle/RunWithMultipleGradleVersionsExtension.groovy) to run the integration tests against multiple Gradle versions. For that, we run each spec multiple times and use [parameter injection](https://spockframework.org/spock/docs/1.3/all_in_one.html#_injecting_method_parameters) to get the version available. This extension works as expected using Spock 1.3.

But when I upgrade to Spock 2, it no longer works. I saw that the `arguments` arrays now has the right size, whereas in the 1.x version it could be smaller and we had to enlarge it.

The problem is that the `arguments` array is empty whereas my `setup` method has one parameter that should be injected. For this reason, if I set the first argument to the value I want to inject, I get a `java.lang.ArrayIndexOutOfBoundsException: Index 0 out of bounds for length 0` error.

If I try to enlarge the `arguments` array as it was necessary in previous versions, I get a `java.lang.IllegalArgumentException: length of arguments array must not change from 0 to 1`. `MethodInvocation` does not let me set one argument since the method has no arguments (which is wrong).

It sounds like the cause of the issue is that the `MethodInvocation` contains some wrong information.

# How to reproduce
I created a [GitHub project](https://github.com/bsautel/spockframework-extension-bug) that shows this issue. Run `./gradlew build` to execute it.

# Additional Environment information

## Java/JDK
```
openjdk version "11.0.10" 2021-01-19
OpenJDK Runtime Environment (build 11.0.10+9-Ubuntu-0ubuntu1.20.04)
OpenJDK 64-Bit Server VM (build 11.0.10+9-Ubuntu-0ubuntu1.20.04, mixed mode, sharing)
```

## Groovy version
3.0.7

### Gradle
6.8.3

## Operating System
Ubuntu 20.04

## IDE
IntelliJ

### Gradle/Grails
`testImplementation("org.spockframework:spock-core:2.0-M4-groovy-3.0")`

Hope this will help to solve this issue. Feel free to ask me further information if needed. Thanks a lot for your work!

### PR DESCRIPTION
**Pull request by Vampire**
fixes #1305

### CODE REVIEW

File: spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy [hunk 1]
```diff
@@ -189,4 +196,78 @@ def foo(x, y) {
...
+    ]
+  }
+
+  static class FooExtension implements IAnnotationDrivenExtension<Foo> {
+    @Override
+    void visitFixtureAnnotation(Foo annotation, MethodInfo fixtureMethod) {
+      fixtureMethod.addInterceptor {
+        assert it.arguments.size() == 1
+        assert it.arguments.first() == MISSING_ARGUMENT
+        it.arguments[0] = null
```
Comment (leonard84) [inline spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy:264]: I'd prefer a String here, e.g.,  `foo`

File: spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java [hunk 2]
```diff
@@ -122,12 +124,23 @@
...
       if (arguments[i] == MISSING_ARGUMENT) {
-        StringJoiner missingArguments = new StringJoiner("', '", "No argument was provided for parameters: '", "'");
-        List<String> parameterNames = getFeature().getParameterNames();
-        missingArguments.add(parameterNames.get(i));
-        for (int j = i + 1; j < argCount; j++) {
-          if (arguments[j] == MISSING_ARGUMENT) {
-            missingArguments.add(parameterNames.get(j));
+        StringJoiner missingArguments;
+        if (getKind() == FEATURE) {
+          missingArguments = new StringJoiner("', '", "No argument was provided for parameters: '", "'");
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java:129]: both are initialized with the same value, so you could move it up to the declaration

File: spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java [hunk 3]
```diff
@@ -122,12 +124,23 @@
...
+            if (arguments[j] == MISSING_ARGUMENT) {
+              missingArguments.add(parameterNames.get(j));
+            }
+          }
+        } else {
+          missingArguments = new StringJoiner(", ", "No argument was provided for parameters: ", "");
+          missingArguments.add(String.valueOf(i));
+          for (int j = i + 1; j < argCount; j++) {
+            if (arguments[j] == MISSING_ARGUMENT) {
+              missingArguments.add(String.valueOf(j));
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java:142]: you need another test with two parameters to hit this

File: spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java [hunk 4]
```diff
@@ -122,12 +124,23 @@
...
+          List<String> parameterNames = getFeature().getParameterNames();
+          missingArguments.add(parameterNames.get(i));
+          for (int j = i + 1; j < argCount; j++) {
+            if (arguments[j] == MISSING_ARGUMENT) {
+              missingArguments.add(parameterNames.get(j));
+            }
+          }
+        } else {
+          missingArguments = new StringJoiner(", ", "No argument was provided for parameters: ", "");
+          missingArguments.add(String.valueOf(i));
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java:139]: I would use `getReflection().getParameters()[i].getName()` it eithers gives `arg<i>` or the real name when compiled with `-parameters`, would need to check for Groovy's behavior

File: spock-core/src/main/java/org/spockframework/runtime/PlatformSpecRunner.java [hunk 5]
```diff
@@ -384,15 +376,26 @@ protected void invoke(SpockExecutionContext context, Object target, MethodInfo m
     if (method == null || method.isExcluded()) {
       return;
     }
+
+    Object[] methodArguments;
+    int parameterCount = method.getReflection() == null ? arguments.length : method.getReflection().getParameterCount();
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/runtime/PlatformSpecRunner.java:381]: in which cases is it possible to for `method.getReflection()`  return `null` ? If that is possible, then you'll have to handle it when accessing the method parameters as I sugested in `MethodInfo`

**Review by leonard84 — CHANGES_REQUESTED** [review]

File: spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java (hunk 2 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java:129]: No, they are not.
The ones with names get quotes around, the ones with indexes not.

File: spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java (hunk 4 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java:139]: Good point

File: spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java (hunk 2 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/runtime/model/MethodInfo.java:129]: Well, with `parameters[i].getName()` now, I made both cases with quotes, so now they are the same again. :-)

File: spock-core/src/main/java/org/spockframework/runtime/PlatformSpecRunner.java (hunk 5 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/runtime/PlatformSpecRunner.java:381]: Actually I didn't investigate whihc case it is, but I got a NPE during my tests without the `null`-check.

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/runtime/PlatformSpecRunner.java:381]: All that call the `org.spockframework.runtime.model.MethodInfo#MethodInfo(org.spockframework.runtime.model.Invoker)` constructor do not have a `reflection` set.
Those are the 9 that are created in `org.spockframework.runtime.PlatformSpecRunner#createMethodInfoForDoRun...`.
They are synthetic method infos that then delegate to the actual methods but they have no real method as backing.
But in those cases, the method parameter accessing is not a problem, because the accessing is only done if at least one of the arguments is matching `MISSING_ARGUMENT` and that can never happen for those.

**Review by leonard84 — APPROVED** [review]
