### PR TITLE
Fix name clashes where variables that are named like method calls destroy the method call (#1200)

### LINKED ISSUE #1200: Migrating to Spock 2, some errors happen when using parameter named `build`
# Issue description
When migrating to Spock 2, some tests previously green started failing. As crazy as it sounds, it turned out that renaming the parameters named `build` holding a `Mock` to some other name made the tests green again. 

# How to reproduce
- Check out https://github.com/etiennestuder/teamcity-build-scan-plugin
- Run `gradlew build` 
- Change `sbuild` to `build` [here](https://github.com/etiennestuder/teamcity-build-scan-plugin/blob/master/src/test/groovy/nu/studer/teamcity/buildscan/internal/CachedBuildScanLookupTest.groovy#L27)
- --> test will fail

## Link to a gist or similar (optional)
See this code change which turns the red tests back into green tests:
https://github.com/etiennestuder/teamcity-build-scan-plugin/commit/75bfa6dd3b536a7bd85e567140e828c2e1268b28#diff-9dac7f911ea3895bc8e7af5798850b91R26

# Additional Environment information

------------------------------------------------------------
Gradle 6.6-rc-2
------------------------------------------------------------

Kotlin:       1.3.72
Groovy:       2.5.12
Ant:          Apache Ant(TM) version 1.10.8 compiled on May 10 2020
JVM:          13.0.2 (Oracle Corporation 13.0.2+8)
OS:           Mac OS X 10.15.6 x86_64

## Java/JDK
openjdk version "13.0.2" 2020-01-14
OpenJDK Runtime Environment (build 13.0.2+8)
OpenJDK 64-Bit Server VM (build 13.0.2+8, mixed mode, sharing)

### Gradle/Grails
dependencies {
    testImplementation 'org.spockframework:spock-core:2.0-M3-groovy-2.5'
    testImplementation 'org.spockframework:spock-junit4:2.0-M3-groovy-2.5'
}

test {
    useJUnitPlatform()
}

### PR DESCRIPTION
**Pull request by Vampire**
This happened due to a buggy VariableScopeVisitor as reported in https://issues.apache.org/jira/browse/GROOVY-9651

fixes #1200 

---
This change is [Reviewable](https://reviewable.io/reviews/spockframework/spock/1201)

### CODE REVIEW

File: spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java [hunk 1]
```diff
@@ -81,7 +118,50 @@
...
+    InteractionBuilder.getDeclaredMethods(org.spockframework.mock.runtime.InteractionBuilder.ADD_WILDCARD_TARGET).get(0);
+  public final MethodNode InteractionBuilder_AddEqualMethodName =
+    InteractionBuilder.getDeclaredMethods(org.spockframework.mock.runtime.InteractionBuilder.ADD_EQUAL_METHOD_NAME).get(0);
+  public final MethodNode InteractionBuilder_AddRegexMethodName =
+    InteractionBuilder.getDeclaredMethods(org.spockframework.mock.runtime.InteractionBuilder.ADD_REGEX_METHOD_NAME).get(0);
+  public final MethodNode InteractionBuilder_AddEqualPropertyName =
+    InteractionBuilder.getDeclaredMethods(org.spockframework.mock.runtime.InteractionBuilder.ADD_EQUAL_PROPERTY_NAME).get(0);
+  public final MethodNode InteractionBuilder_AddRegexPropertyName =
+    InteractionBuilder.getDeclaredMethods(org.spockframework.mock.runtime.InteractionBuilder.ADD_REGEX_PROPERTY_NAME).get(0);
+  public final MethodNode InteractionBuilder_SetArgListKind_boolean_boolean =
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java:137]: This seems to be the only instance where the parameters are listed.

File: spock-core/src/main/java/org/spockframework/compiler/AstUtil.java [hunk 2]
```diff
@@ -329,15 +337,7 @@ public static Expression getVariableType(BinaryExpression assignment) {
...
-    return new MethodCallExpression(expression,
-                                    GET_AT_METHOD_NAME,
-                                    new ConstantExpression(index));
-  }
-
-  public static MethodCallExpression createGetMethod(Expression expression, int index) {
-    return new MethodCallExpression(expression,
-                                    GET_METHOD_NAME,
-                                    new ConstantExpression(index));
+  public static MethodCallExpression createGetAtMethodCall(Expression expression, int index) {
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/compiler/AstUtil.java:340]: Why don't we nee the normal `get` anymore?

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/AstUtil.java:340]: Because this is now done as direct call: https://github.com/spockframework/spock/pull/1201/files#diff-93ae30b9276f36a9d9554475ec30262eL529-R537

File: spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java (hunk 1 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/AstNodeCache.java:137]: Because it is the only method that has overloads.
