### PR TITLE
Fix ExceptionAdapterExtension to also handle inherited fixture methods

### LINKED ISSUE #1263: JUnit4 assumptions fail the tests when coming from setup() method of a super spec
# Issue description
JUnit4 assumptions fail the tests when coming from `setup()` method of a super spec.
When debugging, it looks like the `MethodInfo` of the `setup` method does not have any interceptors in the failing case. Specifically, the `ExceptionAdapterInterceptor` that handles this case in the working case is missing.

# How to reproduce
Repository with minimal reproducer: https://github.com/rieske/spock-junit4-assumptions-reproducer

Assumptions are handled correctly when this spec is executed:
```
class SuperSpec extends Specification {
    def setup() {
        assumeTrue(false)
    }

    def "super feature"() {
        expect:
        true
    }
}
```

Assumptions from super spec's `setup()` method fail as errors when this one is executed:
```
class SubSpec extends SuperSpec {
    def "sub feature"() {
        expect:
        true
    }
}
```

## Build-tool dependencies used

```
testImplementation("org.spockframework:spock-core:2.0-M4-groovy-2.5")
testImplementation("org.spockframework:spock-junit4:2.0-M4-groovy-2.5")
```

### PR DESCRIPTION
**Pull request by leonard84**
fixes #1263

### CODE REVIEW

File: spock-junit4/src/test/groovy/org/spockframework/junit4/junit/ExceptionAdapterSpec.groovy [hunk 1]
```diff
@@ -15,6 +17,49 @@ class ExceptionAdapterSpec extends JUnitBaseSpec {
...
+      testsStartedCount == testsStarted
+      testsAbortedCount == testsAbortet
+      testsSucceededCount == testsSucceeded
+      containersAbortedCount == containersAborted
+      containersStartedCount == 3 // engine + 2 specs
+      testsFailedCount == 0
+    }
+
+    where:
+    fixtureMethod | testsStarted | testsAbortet | testsSucceeded | containersAborted
```
Comment (marcphilipp) [inline spock-junit4/src/test/groovy/org/spockframework/junit4/junit/ExceptionAdapterSpec.groovy:56]:
```suggestion
      testsAbortedCount == testsAborted
      testsSucceededCount == testsSucceeded
      containersAbortedCount == containersAborted
      containersStartedCount == 3 // engine + 2 specs
      testsFailedCount == 0
    }

    where:
    fixtureMethod | testsStarted | testsAborted | testsSucceeded | containersAborted
```

**Review by marcphilipp — APPROVED** [review]
