### PR TITLE
Fix @Verify and @VerifyAll method compilation (#2150)

### LINKED ISSUE #2150: `Verify` blows up with `groovy.lang.MissingPropertyException`
### Describe the bug

```groovy
@Verify
private void foo(a, b) {
  a.every { it == b }
}
```

And call it with `foo([1, 2, 3], 2)`. Leads to:

```
a.every { it == b }
| |
| groovy.lang.MissingPropertyException: No such property: $spock_errorCollector for class: com.company.SomeSpec
|   at com.company.SomeSpec.foo_closure3(SomeSpec.groovy:234)
|   at com.company.SomeSpec.foo(SomeSpec.groovy:234)
|   at com.company.SomeSpec.bar(SomeSpec.groovy:219)
[1, 2, 3]
    at app//com.company.SomeSpec.foo(SomeSpec.groovy:234)
    at com.company.SomeSpec.bar(SomeSpec.groovy:219)

    Caused by:
    groovy.lang.MissingPropertyException: No such property: $spock_errorCollector for class: com.company.SomeSpec
        at com.profuzdigital.data_server.types.SomeSpec.foo_closure3(SomeSpec.groovy:234)
        ... 2 more
```

### To Reproduce

Check the code above.

### Expected behavior

No error.

### Actual behavior

The error above.

### Java version

openjdk version "24.0.1" 2025-04-15

### Buildtool version

Gradle 8.14-rc-2

### What operating system are you using

Linux

### Dependencies

Just Spock.

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by Vampire**
Fixes #2150

### CODE REVIEW

**Comment by Vampire** [comment]
* **#2249** <a href="https://app.graphite.com/github/pr/spockframework/spock/2249?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.com/github/pr/spockframework/spock/2249?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `master`


<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by Vampire** [comment]
This hopefully fixes the mess with the `@Verify` and `@VerifyAll` methods

File: spock-specs/src/test/groovy/org/spockframework/smoke/VerifyMethodsSpecification.groovy [hunk 1]
```diff
@@ -22,18 +22,19 @@ import spock.lang.Verify
 class VerifyMethodsSpecification extends Specification {
 
   @Verify
-  private static void isPositive(int x) {
+  private static isPositive(int x) {
```
Comment (AndreasTu) [inline spock-specs/src/test/groovy/org/spockframework/smoke/VerifyMethodsSpecification.groovy:25]: Is the removal of `void` required?
As the docu state this should not be necessary.

You removed this in a bunch of places.
If this needs to change, then this should also be marked as a breaking change in the release notes.

Update: The production code reads as it also allows `void` so why change it here?

File: spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/VerifyAllMethodsAstSpec/interactions_are_illegal_in_verify_methods.groovy [hunk 2]
```diff
@@ -0,0 +1,7 @@
+Unable to produce AST for this phase due to earlier compilation error:
+startup failed:
+script.groovy: 5: Interactions are not allowed in 'verify' blocks. Put them before the 'verify' block or into a 'then' block. @ line 5, column 9.
```
Comment (AndreasTu) [inline spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/VerifyAllMethodsAstSpec/interactions_are_illegal_in_verify_methods.groovy]: The error message is a bit strange.
The verify block is in a method, so there is no way "to put them before the block".

File: spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java [hunk 3]
```diff
@@ -72,7 +75,7 @@ private String getValueRecorderSuffix() {
   }
 
   private String getErrorCollectorSuffix() {
-    return groupConditionFound ? String.valueOf(closureDepth) : "";
+    return (groupConditionFound && (closureDepth > 0)) ? String.valueOf(closureDepth) : "";
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java:78]: I do not get that change.
What is the reason for that?

File: spock-core/src/main/java/org/spockframework/compiler/SpecParser.java [hunk 4]
```diff
@@ -176,6 +180,31 @@ private void buildFeatureMethod(MethodNode method) {
     spec.getMethods().add(feature);
   }
 
+  private boolean isVerifyMethod(MethodNode method) {
+    boolean hasVerifyAnnotation = !method.getAnnotations(nodeCache.Verify).isEmpty();
+    boolean hasVerifyAllAnnotation = !method.getAnnotations(nodeCache.VerifyAll).isEmpty();
+    if (hasVerifyAnnotation && hasVerifyAllAnnotation) {
+      errorReporter.error(method, "Method '%s' cannot be annotated with both @Verify and @VerifyAll", method.getName());
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: The error message below ends with a dot.

```suggestion
      errorReporter.error(method, "Method '%s' cannot be annotated with both @Verify and @VerifyAll.", method.getName());
```

File: spock-core/src/main/java/org/spockframework/compiler/SpecParser.java [hunk 5]
```diff
@@ -176,6 +180,31 @@ private void buildFeatureMethod(MethodNode method) {
...
+      return false;
+    }
+    return hasVerifyAnnotation || hasVerifyAllAnnotation;
+  }
+
+  private void buildVerifyMethod(MethodNode method) {
+    if (!method.isVoidMethod() && !method.isDynamicReturnType()) {
+      errorReporter.error("Verification helper method '%s' must have a void or dynamic return type.", method.getName());
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: Maybe we could say what dynamic return type means for users not so samiliar with Groovy.

```suggestion
      errorReporter.error("Verification helper method '%s' must have a void or dynamic return type (none).", method.getName());
```

File: spock-core/src/main/java/org/spockframework/compiler/condition/BaseVerifyMethodTransform.java [hunk 6]
```diff
@@ -38,20 +38,34 @@ public void visit(ASTNode[] astNodes, SourceUnit sourceUnit) {
...
-        processVerificationHelperMethod((MethodNode) node, errorReporter, sourceLookup);
+        if (((MethodNode) node).getDeclaringClass().isDerivedFrom(nodeCache.Specification)) {
+          // SpecRewriter already handles the method, so don't transform it again
+          continue;
+        }
+
+        boolean hasVerifyAnnotation = !((MethodNode) node).getAnnotations(nodeCache.Verify).isEmpty();
+        boolean hasVerifyAllAnnotation = !((MethodNode) node).getAnnotations(nodeCache.VerifyAll).isEmpty();
+        if (hasVerifyAnnotation && hasVerifyAllAnnotation) {
+          errorReporter.error(node, "Method '%s' cannot be annotated with both @Verify and @VerifyAll", ((MethodNode) node).getName());
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/compiler/condition/BaseVerifyMethodTransform.java]:
```suggestion
          errorReporter.error(node, "Method '%s' cannot be annotated with both @Verify and @VerifyAll.", ((MethodNode) node).getName());
```

Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/compiler/condition/BaseVerifyMethodTransform.java]: Maybe extract the logic into a helper method, because this seams the same as in `SpecParser`.

File: spock-core/src/main/java/org/spockframework/compiler/condition/BaseVerifyMethodTransform.java [hunk 7]
```diff
@@ -38,20 +38,34 @@ public void visit(ASTNode[] astNodes, SourceUnit sourceUnit) {
           continue;
         }
 
-        processVerificationHelperMethod((MethodNode) node, errorReporter, sourceLookup);
+        if (((MethodNode) node).getDeclaringClass().isDerivedFrom(nodeCache.Specification)) {
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/compiler/condition/BaseVerifyMethodTransform.java]: Create a local var to 
`MethodNode method = (MethodNode)node;` to remove the three casts etc.

File: spock-core/src/main/java/org/spockframework/compiler/condition/BaseVerifyMethodTransform.java [hunk 8]
```diff
@@ -38,20 +38,34 @@ public void visit(ASTNode[] astNodes, SourceUnit sourceUnit) {
...
     }
   }
 
-  private void processVerificationHelperMethod(MethodNode method, ErrorReporter errorReporter, SourceLookup sourceLookup) {
-    if (!method.isVoidMethod()) {
-      errorReporter.error("Verification helper method '%s' must have a void return type.", method.getName());
+  private void processVerificationHelperMethod(Method method, ErrorReporter errorReporter, SourceLookup sourceLookup) {
+    MethodNode methodAst = method.getAst();
+    if (!methodAst.isVoidMethod() && !methodAst.isDynamicReturnType()) {
+      errorReporter.error("Verification helper method '%s' must have a void or dynamic return type.", method.getName());
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/compiler/condition/BaseVerifyMethodTransform.java]: This is also duplicated with `SpecParser`. Maybe helper method.

File: spock-core/src/main/java/org/spockframework/compiler/condition/VerifyMethodRewriter.java [hunk 9]
```diff
@@ -14,21 +14,32 @@
...
+                            List<Statement> statements) {
+    if (methodHasDeepNonGroupedCondition) {
+      resources.getErrorRecorders().defineErrorRethrower(statements);
+    }
   }
 
+  @Override
+  ISpecialMethodCall createSpecialMethodCall() {
+    return new SpecialMethodCall(Identifiers.WITH, null, null, null,
+      null, null, false, resources.getAstNodeCache());
```
Comment (AndreasTu) [inline spock-core/src/main/java/org/spockframework/compiler/condition/VerifyMethodRewriter.java]: How about a new Constructor or factory method without all these `null` would make it more understandable. Also see `VerifyAllMethodRewriter` for similar code.

File: spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/BaseVerifyMethodsAstSpec.groovy [hunk 10]
```diff
@@ -199,7 +275,7 @@ class SpecificAssertions extends BaseAssertions {
     snapshotter.assertThat(result.source).matchesSnapshot()
   }
 
-  def "fails when verification method has a non-void return value"() {
+  def "fails when verification method has a non-void or -dynamic return value"() {
```
Comment (AndreasTu) [inline spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/BaseVerifyMethodsAstSpec.groovy]:
```suggestion
  def "fails when verification method has a non-void or dynamic return value"() {
```

File: spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/BaseVerifyMethodsAstSpec.groovy [hunk 11]
```diff
@@ -213,7 +289,22 @@ class Assertions {
 
     then:
     MultipleCompilationErrorsException e = thrown()
-    e.message.contains("Verification helper method 'isPositiveWithReturn' must have a void return type.")
+    e.message.contains("Verification helper method 'isPositiveWithReturn' must have a void or dynamic return type.")
+  }
+
+  def "fails when verification method has a non-void or -dynamic return value in Spec"() {
```
Comment (AndreasTu) [inline spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/BaseVerifyMethodsAstSpec.groovy]:
```suggestion
  def "fails when verification method has a non-void or dynamic return value in Spec"() {
```

File: docs/release_notes.adoc [hunk 12]
```diff
@@ -71,6 +71,7 @@ will now require that the spec is annotated with <<parallel_execution.adoc#isola
 
 === Misc
 
+* Fix handling of @Verify and @VerifyAll spockIssue:2150[]
```
Comment (AndreasTu) [inline docs/release_notes.adoc]: Please add a breaking change note, that the methods now must be `void` or none.
This will issue new compile errors, when updating to this version.

**Review by AndreasTu — CHANGES_REQUESTED** [review]

File: spock-core/src/main/java/org/spockframework/compiler/SpecParser.java (hunk 5 above)
Comment (leonard84) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: Why not say `void or def`. I don't really see a reason for people to use `Object`. What do you mean with `(none)`?

File: spock-core/src/main/java/org/spockframework/compiler/IRewriteResources.java [hunk 13]
```diff
@@ -17,14 +17,27 @@
...
 /**
+ *
  * @author Peter Niederwieser
  */
 public interface IRewriteResources {
+  Method getCurrentMethod();
+
+  Block getCurrentBlock();
+
+  VariableExpression captureOldValue(Expression oldValue);
```
Comment (leonard84) [inline spock-core/src/main/java/org/spockframework/compiler/IRewriteResources.java:37]: These don't apply outside of a spec, though.

File: spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/BaseVerifyMethodsAstSpec.groovy (hunk 10 above)
Comment (leonard84) [reply spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/BaseVerifyMethodsAstSpec.groovy]: did you mean `non-dynamic`?

File: spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/VerifyAllMethodsAstSpec/interactions_are_illegal_in_verify_methods.groovy (hunk 2 above)
Comment (leonard84) [reply spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/VerifyAllMethodsAstSpec/interactions_are_illegal_in_verify_methods.groovy]: I agree, as it is now, there is no visible `verify:` block. It is only an implementation detail that we even have it. What about `Interactions are not allowed in '@Verify' and '@VerifyAll' methods.` ?

File: spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/VerifyAllMethodsAstSpec/transforms_conditions_in_methods_inside_spec_classes.groovy [hunk 14]
```diff
@@ -5,9 +5,9 @@ class ASpec extends Specification {
 /*--------- tag::snapshot[] ---------*/
 @spock.lang.VerifyAll
 public void isPositiveAndEven(int a) {
-    org.spockframework.runtime.ValueRecorder $spock_valueRecorder = new org.spockframework.runtime.ValueRecorder()
     org.spockframework.runtime.ErrorCollector $spock_errorCollector = new org.spockframework.runtime.ErrorCollector()
     try {
+        org.spockframework.runtime.ValueRecorder $spock_valueRecorder = new org.spockframework.runtime.ValueRecorder()
```
Comment (leonard84) [inline spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/VerifyAllMethodsAstSpec/transforms_conditions_in_methods_inside_spec_classes.groovy]: Is this an intentional change to move the declaration within the try?

File: spock-core/src/main/java/org/spockframework/compiler/SpecParser.java (hunk 5 above)
Comment (AndreasTu) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: I meant `def` with none. But I like your `void or def` better.

File: docs/release_notes.adoc (hunk 12 above)
Comment (Vampire) [reply docs/release_notes.adoc]: Where do you see a breaking change?
Before my changes only `void` was allowed, so you always had to use `void`.
I weakened it so that also dynamic return type is allowed like `def foo()` or `private foo()` or `static foo()` instead of `void foo()` or `private void foo()` or `static void foo()`, but forcing the return type to be `void` after AST transformation.

So more than before is allowed. You can now have the dynamic return type, but if you try to return something it will still fail compilation.

File: spock-core/src/main/java/org/spockframework/compiler/condition/BaseVerifyMethodTransform.java (hunk 6 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/condition/BaseVerifyMethodTransform.java]: Besides that I changed it now to use `AstUtil.hasAnnotation` instead, I think it is slightly different and not worth extracting. The one just reports an error and continues, the other reports an error and returns. To make this a static helper, you would need to give the error reporter and the target as parameters and either also both `hasAnnotation` results or return both as results as in the spec parser case the boolean results are needed again right after.

File: spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java (hunk 3 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/DeepBlockRewriter.java:78]: This suffix is used when rewriting an implicit or explicit condition.
If you are inside a `verifyAll { ... }` closure (`groupConditionFound`), we define a new error collector inside the closure as it should collect the errors and not immediately report them, and if you have nested ones, you need multiple.
If you are not inside a group condition you just use the directly reporting error rethrower that is defined on the top-level of the method if some condition was found.

Now inside the `@VerifyAll` methods it is slightly different, because there on the method level the error collector is defined and you only need to use the nested ones on closure depth >0, because if you are not inside a closure (`closureDepth == 0`), then you can directly use the top-level reporter.

In the old cases this was not possible as group conditions were always inside a closure.
Here you could either have declared the top-level error reporter with suffix `0` so that the used variable is right, or fix the variable references to match the top-level variable and I decided for the latter.

File: spock-core/src/main/java/org/spockframework/compiler/IRewriteResources.java (hunk 13 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/IRewriteResources.java:37]: That's correct for `captureOldValue` and `getMockInvocationMatcher`, but I wanted to reuse the `DeepBlockRewriter` as it does exactly what we want and trying to reimplement part of its logic is exactly why the current state is as broken as it is. The `DeepBlockRewriter` needs those and I didn't want to rip apart the whole `DeepBlockRewriter` into two halves.

For the non-spec method case, these just throw `UnsupportedOperationException` and return `null` respectiviely, which is fine, as the code paths in the `DeepBlockRewriter` that call these methods can never be hit from those verify method transforms, as `captureOldValue` can only be triggered from `then:` block and `getMockInvocationMatcher` is only called in feature methods and on rewriting interactions, which are now explicitly forbidden in those verification methods just like in `expect` blocks.

Another possibility would be to have them in a sub-interface and make an instance-of check and cast in the `DeepBlockRewriter`, but I thought this solution is better and also more performant.

File: spock-core/src/main/java/org/spockframework/compiler/SpecParser.java (hunk 5 above)
Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: I don't because neither is correct.
I also don't see a reason for `Object` and it should not be allowed.
Only `void` (as before)  and dynamic return type are allowed, while after the transformation it is `void` and fails compilaton if they tried to return a value.

The point is "dynamic-return type" !== `def`, otherwise I wouldn't have changed that dynamic return type is allowed as `def foo() { ... }` does not win much over `void foo() { ... }`.

But what this allows too is writing `static foo() { ... }` and `private foo() { ... }` instead of the need to write `static void foo() { ... }` and `private void foo() { ... }`, and there no `def` is there.

File: spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/BaseVerifyMethodsAstSpec.groovy (hunk 10 above)
Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/BaseVerifyMethodsAstSpec.groovy]: Of course, but as you both seem to not get it, I'll add the `non` explicitly

File: spock-specs/src/test/groovy/org/spockframework/smoke/VerifyMethodsSpecification.groovy (hunk 1 above)
Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/smoke/VerifyMethodsSpecification.groovy:25]: It is not required, but allowed.

But it is the sense of the allowing of dynamic return types, to be able to remove this unnecessary noise for the reader, so I removed it also in our testbase except where it is explicitly tested that it works, to improve the readability of the tests.

So, no, it is not a breaking change as I already said above. :-)

File: spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/VerifyAllMethodsAstSpec/transforms_conditions_in_methods_inside_spec_classes.groovy (hunk 14 above)
Comment (Vampire) [reply spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/VerifyAllMethodsAstSpec/transforms_conditions_in_methods_inside_spec_classes.groovy]: More a side-effect of the order the valurecorder and errorcollector are defined.
The `try` is just for the `finally` to report on the collected errors.
Before it was separate code, so there the order was different as in the code that is reused now.

Comment (Vampire) [reply spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/VerifyAllMethodsAstSpec/transforms_conditions_in_methods_inside_spec_classes.groovy]: If you think it is important, I could move it up again by doing
```diff
diff --git a/spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java b/spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java
index 99cfb0fddc..fd0977aee3 100644
--- a/spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java
+++ b/spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java
@@ -413,14 +413,14 @@ public void visitMethodAgain(Method method) {
       method.getStatements().add(createMockControllerCall(nodeCache.MockController_LeaveScope));
     }

+    boolean verifyAllMethod = method instanceof VerifyAllMethod;
+    if (verifyAllMethod && methodHasCondition) {
+      errorRecorders.defineErrorCollector(method.getStatements());
+    }
     if (methodHasCondition) {
       errorRecorders.defineValueRecorder(method.getStatements());
     }
-    if (method instanceof VerifyAllMethod) {
-      if (methodHasCondition) {
-        errorRecorders.defineErrorCollector(method.getStatements());
-      }
-    } else if (methodHasDeepNonGroupedCondition) {
+    if (!verifyAllMethod && methodHasDeepNonGroupedCondition) {
       errorRecorders.defineErrorRethrower(method.getStatements());
     }
   }
```
Or I can swap the `if`s like this:
```diff
diff --git a/spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java b/spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java
index 99cfb0fddc..1e3931003a 100644
--- a/spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java
+++ b/spock-core/src/main/java/org/spockframework/compiler/SpecRewriter.java
@@ -413,9 +413,6 @@ public void visitMethodAgain(Method method) {
       method.getStatements().add(createMockControllerCall(nodeCache.MockController_LeaveScope));
     }

-    if (methodHasCondition) {
-      errorRecorders.defineValueRecorder(method.getStatements());
-    }
     if (method instanceof VerifyAllMethod) {
       if (methodHasCondition) {
         errorRecorders.defineErrorCollector(method.getStatements());
@@ -423,6 +420,9 @@ public void visitMethodAgain(Method method) {
     } else if (methodHasDeepNonGroupedCondition) {
       errorRecorders.defineErrorRethrower(method.getStatements());
     }
+    if (methodHasCondition) {
+      errorRecorders.defineValueRecorder(method.getStatements());
+    }
   }


```
Then also in all existing cases the two are swapped, so that the value recorder is declared first and the error rethrower second..

Effectively, It should probably all be the same, however you like it most. :-)

File: spock-core/src/main/java/org/spockframework/compiler/SpecParser.java (hunk 5 above)
Comment (AndreasTu) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: >The point is "dynamic-return type" !== def

I do not get that. I do not find any reference of  "dynamic-return type" in the Groovy documentation. Only one tutorial mentioning it and say it is `def`. How are these two different?
I do not think we should use wording in an error message, which is not even part of the Groovy documentation.

And you changed it in one case in the tests from `void` to `def` and not without, so why that?

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]:
```groovy
def String foo() {
   return 'bar'
}
```
This has `def`, but return type is `String`.

```groovy
static foo() {
   return 'bar'
}
private baz() {
   return 'bam'
}
```
These have no `def`, but the return type is dynamic.

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: The terminology I adopted from the Groovy AST method name `org.codehaus.groovy.ast.MethodNode#isDynamicReturnType`.

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: Dynamic return type basically is indeed not specifying any return type, just like you can leave out the type of a method parameter.

Just in some situations like
`foo() { }`
or
`<T> T foo() { null }`
you have to use `def` to make it valid and unambiguous Groovy syntax.

Otherwise the first case could for example be a method call, not sure why the second case needs a `def`, but it does and it does not have a dynamic return type.

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: And the Groovy documentation cannot really hold as reference (even if it should) as it is not correct at all.
It for example says "Methods in Groovy always return some value" which is not true if it is declared as `void`.
It also says "return type or with the `def` keyword" which is not correct as you can also have both and also can have neither.
And it says "`def` keyword, to make the return type untyped" which is also not correct if you specify `def` and a return type.

So the docs are really no good source of truth here as not much truth is found unfortunately.
The truth is, if you do not specify a return type explicitly (like `void` or an actual type), you have a dynamic return type / untyped return type / flexible return type / however you want to name it.
And `def` is just there to disambiguate some cases that would otherwise be unclear to the parser probably, and can even be combined with `void`.

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: I created https://issues.apache.org/jira/browse/GROOVY-11802 to get the Groovy docs fixed.

File: spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/BaseVerifyMethodsAstSpec.groovy [hunk 15]
```diff
@@ -36,7 +36,7 @@ abstract class BaseVerifyMethodsAstSpec extends EmbeddedSpecification {
     when:
     def result = compiler.transpileSpecBody("""
 @${annotation.name}
-void isPositiveAndEven(int a) {
+def isPositiveAndEven(int a) {
```
Comment (AndreasTu) [inline spock-specs/src/test/groovy/org/spockframework/smoke/ast/condition/BaseVerifyMethodsAstSpec.groovy:39]: This is the place I mean with only a `def`

File: spock-core/src/main/java/org/spockframework/compiler/SpecParser.java (hunk 5 above)
Comment (AndreasTu) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: I still think this is missleading as an error message to the users, when even the Groovy guys and we can't agree on a exact meaning here.
An error message should help people, not open up more questions.

So why can't we just say `void or def (dynamic return-type)` in the error message, even if it is not 100% correct.

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: Well, the meaning is obviously what the parser and code mandate and the documentation is plainly wrong. :-)

> So why can't we just say void or def (dynamic return-type) in the error message, even if it is not 100% correct.

Well, because it is not correct, "def" is just "define" and has nothing to do with the return type.
I'm open to better but correct wording.
I as user when I would see that wording would open an error report as it is just wrong. :-)
If @leonard84 as chief maintainer is aware of the plain lie that the statement is and still wants it, I can live with it, but that does not make it any more correct. :-)

> And you changed it in one case in the tests from void to def and not without, so why that?

As I just explained in https://github.com/spockframework/spock/pull/2249#discussion_r2518543852, without the `def` it would not be a valid groovy definition. Like many things in Groovy you can leave out the `def` for the "define a method here" if enough other syntax is present to make it unambiguous, just like you can leave out the parentheses in a method call if the call is unambiguous and has parameters. But if there are no parameters or the syntax is unclear to the parser, you have to use the parentheses. Same here, if it is clear enough because you have other method modifiers or a return type, you can leave out the `def` keyword. But if everything else is left out or if you start with a generic type declaration, you have to add the `def` or it is not valid Groovy syntax. But still it has nothing at all to do with the return type.

Comment (leonard84) [reply spock-core/src/main/java/org/spockframework/compiler/SpecParser.java]: Let's assume that the users are not Groovy experts, so we should be as helpful as possible in the message.

`Verification helper method '%s' must have a void return type or use a dynamic return type ('def' or no declared type).`

Also, align the mention in the docs as well as add examples to `VerifyMethodsDocSpec`, so it showcases all three variants.

File: spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/VerifyAllMethodsAstSpec/transforms_conditions_in_methods_inside_spec_classes.groovy (hunk 14 above)
Comment (leonard84) [reply spock-specs/src/test/resources/snapshots/org/spockframework/smoke/ast/condition/VerifyAllMethodsAstSpec/transforms_conditions_in_methods_inside_spec_classes.groovy]: Let's go with option two; it seems the simplest to achieve the goal of keeping it out of the try block. Switching the order is an acceptable tradeoff.

File: spock-core/src/main/java/org/spockframework/compiler/IRewriteResources.java (hunk 13 above)
Comment (leonard84) [reply spock-core/src/main/java/org/spockframework/compiler/IRewriteResources.java:37]: Shouldn't we at least use a more useful error message in that case, i.e., that it is only supported by `SpecRewriter`/ within a Specification?

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/IRewriteResources.java:37]: For whom?
If the error happens, it is a Spock implementation bug.
The user is not able to trigger this error from a verification method.
If this is ever changed - which is pretty unlikely - then this spot will most probably be adapted anyway.

Comment (leonard84) [reply spock-core/src/main/java/org/spockframework/compiler/IRewriteResources.java:37]: For future us 🙂

Comment (Vampire) [reply spock-core/src/main/java/org/spockframework/compiler/IRewriteResources.java:37]: Ok, I changed it to `throw new UnsupportedOperationException("This should only be called when processing a then-block");` for the old-case.

For the mock invocation matcher I didn't because I lied. :-)
That I did not already throw an UOE there is, because it does get called, but then the result is ignored in case of a `VerifyBlock`.
And the order cannot be swapped, because the result is used for an up-front check whether it is an interaction at all, before then complaining that you must not have one in expect or verify.

File: docs/spock_primer.adoc [hunk 16]
```diff
@@ -582,8 +582,9 @@ Not very helpful. Fortunately, we can do better:
 include::{sourcedir}/primer/VerifyMethodsDocSpec.groovy[tag=verify-helper-method]
 ----
 
-When factoring out conditions into a helper method, you need to ensure the method has return type `void`.
-Otherwise, Spock might interpret the return value as a failing condition, which is not what we want.
+When factoring out conditions into a helper method, you need to ensure the method has return type of `void`,
+or uses a dynamic return type ('def' or no declared type). After compilation it will in both cases be `void` and any
+other return type causes a compilation error, as Spock might interpret the return value as a failing condition otherwise.
```
Comment (leonard84) [inline docs/spock_primer.adoc]: For new documentation, we should follow the [guideline of one sentence per line](https://asciidoctor.org/docs/asciidoc-recommended-practices/#one-sentence-per-line) for Asciidoc.
Also used backticks for `def` to make it fit in with `void`. The rest are changes recommended by Grammarly.

```suggestion
When factoring out conditions into a helper method, you need to ensure the method has a return type of `void`, or uses a dynamic return type (`def` or no declared type). 
After compilation, it will be `void` in both cases, and any other return type causes a compilation error, as Spock might interpret the return value as a failing condition otherwise.
```

File: spock-specs/src/test/groovy/org/spockframework/docs/primer/VerifyMethodsDocSpec.groovy [hunk 17]
```diff
@@ -62,6 +62,41 @@ pc.clockRate >= 2333
...
+    final String os
+}
+
+@Verify
+static matchesPreferredConfiguration(PC pc) {
+  pc.vendor == "Sunny"
+  pc.clockRate >= 2333
+  pc.ram >= 4096
+  pc.os == "Linux"
+}
```
Comment (leonard84) [inline spock-specs/src/test/groovy/org/spockframework/docs/primer/VerifyMethodsDocSpec.groovy:82]: I don't see any tags for inclusion in the docs, or am I missing something?
I thought we agreed to show a short example for 

```
@Verify void method() { ... }
@Verify def method() { ... }
@Verify method() { ... }
```

Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/docs/primer/VerifyMethodsDocSpec.groovy:82]: You said I should add an example to the doc spec, not to also show it in the docs :-)

Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/docs/primer/VerifyMethodsDocSpec.groovy:82]: Besides that the third version is still not valid Groovy, it could be `static method()` or `private method()` for example

Comment (leonard84) [reply spock-specs/src/test/groovy/org/spockframework/docs/primer/VerifyMethodsDocSpec.groovy:82]: Are you [sure](https://groovyconsole.dev/?g=groovy_4_0&codez=eNpNi7EKwjAURfd8xaVT61DoKhTq4ubkF4Tk1QbTvJC8oiL-u2lwcLlwDue6NXIS5Mjm3nsdbv1BKeN1zjhdIxnQUyjYjB3c7IwWxwFvBVia0SzkPePBydum7apH-ZRYjqgADBhHrK8LycK27Yr9qDLTmflP_76JZEsBQ61KN7kglGZtCHu_R0V_AcFENmo)?

Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/docs/primer/VerifyMethodsDocSpec.groovy:82]: Oh, ok, obviously not. :-D
Seems an annotation is also good enough to make it unambiguous. :-)

**Review by leonard84 — DISMISSED** [review]
