### PR TITLE
Fix void methods with implicit targets failing in `with` and `verifyAll`

### LINKED ISSUE #886: verifyAll fails for void conditions
```groovy
  def "verifyAll works with void methods"() {
    expect:
    verifyAll {
      checkCondition()
    }
  }

  void checkCondition() {
    assert true
  }
```
should pass but fails with
```
Condition not satisfied:

checkCondition()
|
null
```

### PR DESCRIPTION
**Pull request by leonard84**
fixes #886

### CODE REVIEW

File: spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java [hunk 1]
```diff
@@ -117,6 +118,15 @@ public static void verifyMethodCondition(@Nullable ErrorCollector errorCollector
     }
   }
 
+  private static boolean isVoidMethod(@Nullable Object target, String method, Object... args) {
+    if (target instanceof Closure) { // since we support verifyAll we must check the closure hierarchy
+      Closure closure = ((Closure)target);
+      return GroovyRuntimeUtil.isVoidMethod(closure.getDelegate(), method, args)
```
Comment (szpak) [inline spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java]: Couldn't `delegate` be a `Closure` for nested `Closure`?

File: spock-specs/src/test/groovy/org/spockframework/smoke/WithBlocks.groovy [hunk 2]
```diff
@@ -16,7 +16,7 @@
 package org.spockframework.smoke
 
 import org.spockframework.runtime.SpockAssertionError
-import spock.lang.Specification
+import spock.lang.*
```
Comment (szpak) [inline spock-specs/src/test/groovy/org/spockframework/smoke/WithBlocks.groovy]: I wonder why it was needed to change?

File: spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java (hunk 1 above)
Comment (szpak) [reply spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java]: (in general in Groovy if set programatically - I don't know it there is a real life scenario for that, but maybe calling `isVoidMethod()` instead of `GroovyRuntimeUtil.isVoidMethod()` is safer here)

File: spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java [hunk 3]
```diff
@@ -117,6 +118,15 @@ public static void verifyMethodCondition(@Nullable ErrorCollector errorCollector
...
+        || isVoidMethod(closure.getOwner(), method, args);
```
[the remark this answers is not in the document]
Comment (leonard84) [reply spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java]: The strategy used in `verifyAll`/`with` is `DELEGATE_FIRST` which is represented here. Do you think it is neccessary to check the strategy here?

File: spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java (hunk 1 above)
Comment (szpak) [reply spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java]: As I said I don't know if there is a real life scenario for that. It would need to be a nested Closure with a delegate programatically modified to be the outer `Closure`. I just put your attention that it is possible in Groovy to have a delegate which is `Closure`. I wonder if you see a potential problem with calling `this.isVoidMethod(closure.getDelegate(), ...)` instead (for in case)?

File: spock-specs/src/test/groovy/org/spockframework/smoke/WithBlocks.groovy (hunk 2 above)
Comment (szpak) [reply spock-specs/src/test/groovy/org/spockframework/smoke/WithBlocks.groovy]: Yup, I missed the `Issue`. Thanks.

File: spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java (hunk 1 above)
Comment (leonard84) [reply spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java]: Although it would be possible, I don't think that it would be "correct" from the syntax standpoint. This method is only called within `verifyAll` via `verifyMethodCondition` so I don't see a scenario where this comes to pass, nested closures are not decorated via `verifyMethodCondition` and if it is a method accepting the closure then the return type of the method is what we are looking at.

File: spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java (hunk 3 above)
[the remark this answers is not in the document]
Comment (marcphilipp) [reply spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java]: Nevermind, I missed that.

File: spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java (hunk 1 above)
Comment (marcphilipp) [reply spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java]: Thanks for the explanation! Makes sense to me.

Comment (szpak) [reply spock-core/src/main/java/org/spockframework/runtime/SpockRuntime.java]: The same for me.
