### PR TITLE
Clarify Documentation for global Mocks

### LINKED ISSUE #785: Global Groovy mock doesn't work as expected
Hello, I made a unit test example based on the documentation here:
http://spockframework.org/spock/docs/1.1/interaction_based_testing.html

Specifically, I am following the example under the section: Mocking All Instances of a Type

Here is my code:
```
package library
import spock.lang.Specification

class Publisher {
    def subscribers = []

    def send(event) {
        subscribers.each {
            it.receive(event)
        }
    }
}

interface Subscriber {
    def receive(event)
}

class RealSubscriber implements Subscriber {
    @Override
    def receive(Object event) {
        return null
    }
}


class PublisherSpec extends Specification {


    def "delivers events to all subscribers"() {
        given:
        def pub = new Publisher()
        def sub1 = Mock(Subscriber)
        def sub2 = Mock(Subscriber)
        pub.subscribers << sub1 << sub2

        when:
        pub.send("event")

        then:
        1 * sub1.receive("event")
        1 * sub2.receive("event")
    }

    def "test global mock"() {
        given:
        def pub = new Publisher()
        pub.subscribers << new RealSubscriber() << new RealSubscriber()
        def anySub = GroovyMock(RealSubscriber, global:true)

        when:
        pub.send("event")

        then:
        2 * anySub.receive("event")
    }
}
```
After running these 2 tests, the first one passes. However the second one failed with below error:

```
Too few invocations for:

2 * anySub.receive("event")   (0 invocations)

Unmatched invocations (ordered by similarity):

None



	at org.spockframework.mock.runtime.InteractionScope.verifyInteractions(InteractionScope.java:78)
	at org.spockframework.mock.runtime.MockController.leaveScope(MockController.java:76)
	at library.PublisherSpec.test global mock(PublisherSpec.groovy:51)
```
I would expect the second test passes as well, did I miss something in the test? Please help!

Here is my local env: (and I am using latest spock: spock-core:1.1-groovy-2.4-rc-3)
------------------------------------------------------------
Gradle 4.2
------------------------------------------------------------

Build time:   2017-09-20 14:48:23 UTC
Revision:     5ba503cc17748671c83ce35d7da1cffd6e24dfbd

Groovy:       2.4.11
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_102 (Oracle Corporation 25.102-b14)
OS:           Linux 4.10.0-35-generic amd64

### PR DESCRIPTION
**Pull request by AndreasTu**
Added test case base documentation for global mocks. And clarify the usage of the global mock and lifecycle.

This fixes #785

### CODE REVIEW

File: spock-specs/src/test/groovy/org/spockframework/docs/interaction/GlobalMockDocSpec.groovy [hunk 1]
```diff
@@ -0,0 +1,43 @@
...
+    // end::global-spy[]
+  }
+
+  def "Global mock mocks also constructor"() {
+    // tag::global-mock-constructor[]
+    given:
+    GroovyMock(global: true, RealSubscriber)
+    when:
+    def sub = new RealSubscriber()
+    then: "The GroovyMock(global: true) will also mock the constructor"
```
Comment (leonard84) [inline spock-specs/src/test/groovy/org/spockframework/docs/interaction/GlobalMockDocSpec.groovy:33]: Could you also add an example on how to mock it, to return a valid instance if that es even possible.

File: docs/interaction_based_testing.adoc [hunk 2]
```diff
@@ -942,18 +933,33 @@ real subscribers to the mock object. The mock object's instance isn't ever passe
 it is only used to describe the interaction.
 
 NOTE: A global mock can only be created for a class type. It effectively replaces
-all instances of that type for the duration of the feature method.
+all instances of that type for the duration from mock creation up until the end of the feature method.
+
+CAUTION: The order of declaration global mocks is relevant.
+         The `GroovySpy(global:true)` must come before all creations of new mocked/spied objects.
```
Comment (leonard84) [inline docs/interaction_based_testing.adoc:939]: I don't think this is entirely clear, is that just for instances of the spied upon class or all other mocks?

**Review by leonard84 — CHANGES_REQUESTED** [review]

File: docs/interaction_based_testing.adoc (hunk 2 above)
Comment (AndreasTu) [reply docs/interaction_based_testing.adoc]: I have added a bit more text to clarify this.

**Review by leonard84 — APPROVED** [review]
