### PR TITLE
Cast data variables with type coercion to the declared parameter type (#1279)

### LINKED ISSUE #1279: Spock with Strong Types
# Issue description

Is there a way to create **data-driven tests** with Spock that use explicit or implicit **type conversion**?

In my [sample project](https://github.com/Richargh/spock-strong-types-krdl-kt-sandbox/) I have classes like `Age` or `Name` that wrap `Integer` and `String` plus a `Person { Name name; Age age; }` that uses them. I'd like to write my data like so:

```groovy
def "a test"(Name name, Age age){
    where:
    name      | age
    "John"    | 5
    "Lisa"     | 2
}
```

or like this:

```groovy
def "a test"(Person person){
    where:
    name      | age
    "John"    | 5
    "Lisa"     | 2
}
```

What I don't want to do is to write it like this, because that creates a lot of noise in the test:

```groovy
def "a test"(Name name, Age age){
    where:
    name                   | age
    Name.of("John") | new Age(5)
    Name.of("Lisa")  | new Age(2)
}
```

I've written a Groovy type coercion extension method from String to Person but Spock does not want to use it. 

JUnit5 automatically uses a static factory for type conversion or I can supply an ArgumentConverter/ArgumentAggregator. Can I do something similar in Spock?

# How to reproduce

## Link to a gist or similar (optional)

I created a [sample test](https://github.com/Richargh/spock-strong-types-krdl-kt-sandbox/blob/main/main/src/test/groovy/de/richargh/sandbox/spock/strongtypes/PersonSpecification.groovy) if you want to take a look.

# Additional Environment information

* Java 11
* Spock: "2.0-M4-groovy-3.0"
* Groovy: "3.0.7"
* Gradle 6.8.2
* Mac OS X

### PR DESCRIPTION
**Pull request by Vampire**
fixes #1279

### CODE REVIEW

File: spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy [hunk 1]
```diff
@@ -176,4 +176,17 @@ def foo(x, y) {
     SpockExecutionException see = thrown()
     see.message == /No argument was provided for parameters: 'x', 'y'/
   }
+
+  @Issue("https://github.com/spockframework/spock/issues/1279")
+  def "data values are casted with type-coercion"(Integer x, Integer y) {
```
Comment (szpak) [inline spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy:181]: Looking at code, it should also work for `int`. Maybe you could change `y` to `int y` to cover it by a test?

**Review by szpak — CHANGES_REQUESTED** [review]

**Review by szpak — CHANGES_REQUESTED** [review]
Nice change, in general.

File: spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy (hunk 1 above)
Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy:181]: Sure I can change that, but the type will still be `Integer`
If you type in a Groovy console
```groovy
int i = 1
i.getClass()
```
you also get `Integer` as result.
It works with any type coercion, even custom ones. :-)

Comment (Vampire) [reply spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy:181]: Sure I can change that, but the type will still be `Integer`
If you type in a Groovy console
```groovy
int i = 1
i.getClass()
```
you also get `Integer` as result.
It works with any type coercion, even custom ones. :-)

Comment (szpak) [reply spock-specs/src/test/groovy/org/spockframework/smoke/parameterization/MethodParameters.groovy]: Yes, I know. I meant, put `int y` in the method declaration - which is usually more natural for people than using `Integer` - to have regression tests verifying also that.

**Review by szpak — APPROVED** [review]

File: docs/data_driven_testing.adoc [hunk 2]
```diff
@@ -371,6 +371,19 @@ Data tables, data pipes, and variable assignments can be combined as needed:
 include::{sourcedir}/datadriven/DataSpec.groovy[tag=combined-variable-assignment]
 ----
 
+== Type Coercion for Data Variable Values
+
+Data variable values are casted to the declared parameter type using
```
Comment (leonard84) [inline docs/data_driven_testing.adoc:376]:
```suggestion
Data variable values are coerced to the declared parameter type using
```
otherwise the verb `cast` is irregular https://www.usingenglish.com/reference/irregular-verbs/cast.html but I'm not 100% sure if that applies to the programming term.

File: docs/data_driven_testing.adoc [hunk 3]
```diff
@@ -371,6 +371,19 @@ Data tables, data pipes, and variable assignments can be combined as needed:
...
+https://groovy-lang.org/operators.html#_coercion_operator[type coercion]. Due to that custom type conversions can be
+provided as https://groovy-lang.org/metaprogramming.html#_extension_modules[extension module] or with the help of
+the <<extensions.adoc#_use,`@Use`>> extension on the specification (as it has no effect to the `where:` block if
```
Comment (leonard84) [inline docs/data_driven_testing.adoc:379]: Could you add a test to demonstrate the `@Use` extension, as a user it is really helpful if you can start from a working example.

**Review by leonard84 — CHANGES_REQUESTED** [review]

File: docs/data_driven_testing.adoc (hunk 3 above)
Comment (Vampire) [reply docs/data_driven_testing.adoc:379]: The example is fully working, as there is a standard coercion from `String` to `Integer` which is why I chose it as example. A plain cast would fail, with coercion it is parsed as integer.

Don't you think a full example with `@Use` would be too verbose here?
You would need the class doing the coercion and a full specification as you have to put the `@Use` annotation to the specification for it to work on the generated helper methods.

Comment (leonard84) [reply docs/data_driven_testing.adoc:379]: If you worry about space in the docs we could put it in collapsible blocks, and optionally put the example in an embedded spec:
```
[%collapsible]
====
[source,groovy,indent=0]
----
include::{sourcedir}/datadriven/DataSpec.groovy[tag=type-coercion-at-use]
----
====
```
Alternatively, we could refer them to the specification code.

I recently used the ratpack documentation and found that I was quite missing example code. Think about it, if you don't want to do it, then I'll merge without the example.

**Review by leonard84 — APPROVED** [review]
