### PR TITLE
Fix SpringSpy not working with DirtiesContext...

### LINKED ISSUE #1790: @SpringSpy does not work with @DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
### Describe the bug

`@SpringSpy` does not work in specifications that declare the Spring context dirty in mode `DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD`. Problem may be related to this issue reported against Spring Boot https://github.com/spring-projects/spring-boot/issues/11903

### To Reproduce

Run the following test adapted from the Spring Boot issue.

```groovy
import org.spockframework.spring.SpringSpy
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.stereotype.Component
import org.springframework.stereotype.Service
import org.springframework.test.annotation.DirtiesContext
import spock.lang.Specification

import javax.inject.Inject

@SpringBootTest
// this does not work
@DirtiesContext(classMode = DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD)
// this works
//@DirtiesContext(classMode = DirtiesContext.ClassMode.AFTER_EACH_TEST_METHOD)
class DirtiesContextTest extends Specification {

    @Inject
    MyService myService;

    @SpringSpy
    SpyMe spyMe;

    def 'should call spy'() {
        when:
        myService.serviceMethod();

        then:
        1 * spyMe.someMethod()
    }
}

@Service
class MyService {

    @Inject
    private SpyMe spyMe;

    void serviceMethod() {
        spyMe.someMethod();
    }
}

@Component
class SpyMe {

    void someMethod() {
        System.out.println("SpyMe.someMethod() was called");
    }
}
```

### Expected behavior

The SpringSpy can be used to track invocations.

### Actual behavior

Test fails.

### Java version

Java 17

### Buildtool version

```
------------------------------------------------------------
Gradle 7.4.2
------------------------------------------------------------

Build time:   2022-03-31 15:25:29 UTC
Revision:     540473b8118064efcc264694cbcaa4b677f61041

Kotlin:       1.5.31
Groovy:       3.0.9
Ant:          Apache Ant(TM) version 1.10.11 compiled on July 10 2021
JVM:          17.0.6 (Private Build 17.0.6+10-Ubuntu-0ubuntu120.04.1)
OS:           Linux 5.10.102.1-microsoft-standard-WSL2 amd64

```

### What operating system are you using

Linux

### Dependencies

NA

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leonard84**
DirtiesContext.ClassMode.BEFORE_EACH_TEST_METHOD
fixes #1790

### CODE REVIEW

File: spock-spring/src/main/java/org/spockframework/spring/SpringMockTestExecutionListener.java [hunk 1]
```diff
@@ -36,12 +37,19 @@
...
 
   public static final String MOCKED_BEANS_LIST = "org.spockframework.spring.SpringMockTestExecutionListener.MOCKED_BEANS_LIST";
 
   private final MockUtil mockUtil = new MockUtil();
 
+  @Override
+  public int getOrder() {
+    // needs to run before the DependencyInjectionTestExecutionListener
+    // https://github.com/spockframework/spock/issues/1790
+    return 1955;
```
Comment (AndreasTu) [inline spock-spring/src/main/java/org/spockframework/spring/SpringMockTestExecutionListener.java:50]: This is very arbitary, but I guess that is for the other order `2000` in class `DependencyInjectionTestExecutionListener`.

**Review by AndreasTu — APPROVED** [review]
