### PR TITLE
Fix issues with Spring 6/Spring Boot 3

### LINKED ISSUE #1539: Spock Spring module does not work with Spring Test 6
### Describe the bug

When using Spring Test 6 (used by Spring 6/Boot 3) then the Spock Spring module does not detect the Spring tests. The tests are still picked up and an attempt to execute them is made, but the Spring Application Context is never started.

The issue seems to be caused by the class `org.springframework.test.util.MetaAnnotationUtils` which was deprecated in 5.3 being removed in 6. It looks like Spock used this utility class to discover the `@BootstrapWith` meta-annotation on the `@SpringBootTest` annotation. 

There are separate checks for `@ContextHierarchy` and `@ContextConfiguration`, so if a Spec is using these directly then the Application Context starts as expected.

**Workaround**
Add an empty `@ContextConfiguration` annotation to the Spec.

### To Reproduce

```
@SpringBootTest(classes = [DemoApplication, JustATestSpec])
class JustATestSpec extends Specification implements ApplicationListener<ApplicationReadyEvent> {
	
	static boolean contextSeenStarting = false
	
	@Override
	void onApplicationEvent(ApplicationReadyEvent event) {
		contextSeenStarting = true
	}

	void "Starts Application Context"() {
		expect:
		contextSeenStarting
	}
}

```

### Expected behavior

Application context starts

### Actual behavior

Application context doesn't start

### Java version

All

### Buildtool version

All

### What operating system are you using

Linux

### Dependencies

?

### Additional context

_No response_

### PR DESCRIPTION
**Pull request by leonard84**
fixes #1539

### CODE REVIEW

File: spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/WebMvcTestIntegrationSpec.groovy [hunk 1]
```diff
@@ -0,0 +1,66 @@
...
+      .andExpect(content().string("hello world"))
+  }
+
+  @TestConfiguration
+  static class MockConfig {
+    def detachedMockFactory = new DetachedMockFactory()
+
+    @Bean
+    HelloWorldService helloWorldService() {
+      return detachedMockFactory.Stub(HelloWorldService)
```
Comment (szpak) [inline spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/WebMvcTestIntegrationSpec.groovy:62]: Do you see a need to test also `@SpringBean` and `SpringSpy`? Or it should always work in Spring Boot 3 (assuming tests for Spring Boot 2 pass)?

File: spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/SpringBootTestAnnotationScopedProxyMockSpec.groovy [hunk 2]
```diff
@@ -0,0 +1,76 @@
...
+import spock.mock.DetachedMockFactory
+
+import org.springframework.beans.factory.annotation.Autowired
+import org.springframework.boot.test.context.*
+import org.springframework.context.ApplicationContext
+import org.springframework.context.annotation.*
+import org.springframework.web.context.annotation.RequestScope
+
+/**
+ * Tests enabled scanning of scoped and proxied beans.
```
Comment (szpak) [inline spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/SpringBootTestAnnotationScopedProxyMockSpec.groovy:31]: WDYT about testing testing also `UnwrapAopProxyExtension` in Spring 6/Boot 3?

Comment (leonard84) [reply spock-spring/boot3-test/src/test/groovy/org/spockframework/boot3/SpringBootTestAnnotationScopedProxyMockSpec.groovy:31]: Maybe when I figure out a good way to not copy and paste all the tests from `spock-spring/src/test`, but share them across all the spring (boot) projects, while also taking into account what doesn't work cross version.
